### ISSUE TITLE
Question: Channels (api/channels.md) - Can I publish data after hook in custom service only channel "testRoom"

### ISSUE THREAD

**Issue by lagmanzaza** [feathersjs/docs#1000]

**Comment by lagmanzaza** [comment]
I use  hook.app.publish()

**Comment by daffl** [comment]
Yep, that is it. I would note that the publishing function in `.publish` only needs to be registered once.

**Comment by lagmanzaza** [comment]
I have a question.

Can I join a room in Hook function

**Comment by daffl** [comment]
You should update the assigned channels in an event handler. See https://github.com/feathersjs/docs/issues/950#issuecomment-352301687

**Comment by lagmanzaza** [comment]
Thank you very much. Now I confuse that new real-time transport in FeathersJS v3 ,so I will try to migrate my product into FeathersJS V3.
