### ISSUE TITLE
Comment: Processing data (guides/chat/processing.md)

### ISSUE THREAD

**Issue by uinz** [feathersjs/docs#1001]
![image](https://user-images.githubusercontent.com/12208108/34469438-ba5aeeba-ef59-11e7-85a5-95ba854d5630.png)

run `feathers generate hook`

cli did not ask me `what method should  the hook be for`

```json
  "dependencies": {
    "@feathersjs/authentication": "^2.1.0",
    "@feathersjs/authentication-jwt": "^1.0.1",
    "@feathersjs/authentication-local": "^1.0.2",
    "@feathersjs/configuration": "^1.0.1",
    "@feathersjs/errors": "^3.2.0",
    "@feathersjs/express": "^1.1.2",
    "@feathersjs/feathers": "^3.0.2",
    "compression": "^1.7.1",
    "cors": "^2.8.4",
    "feathers-nedb": "^3.0.0",
    "helmet": "^3.9.0",
    "nedb": "^1.8.0",
    "serve-favicon": "^2.4.5",
    "winston": "^2.4.0"
  }
```
![image](https://user-images.githubusercontent.com/12208108/34469447-f35bf830-ef59-11e7-9dd5-f6b3f1046803.png)

**Comment by daffl** [comment]
When you don't select any services it will not ask for which methods. When you see the list of service, select them with the space key before hitting enter.

**Comment by uinz** [comment]
@daffl Thanks, I forget press space to select, I just press enter
