### ISSUE TITLE
Comment: Server (api/authentication/server.md)

### ISSUE THREAD

**Issue by uinz** [feathersjs/docs#1006]
What different between each auth strategies?

**Comment by daffl** [comment]
That should be documented in each strategy API docs.

- [Local](https://docs.feathersjs.com/api/authentication/local.html): username (email) / password
- [JWT](https://docs.feathersjs.com/api/authentication/jwt.html): JSON web token (see [jwt.io](https://jwt.io/))
- [OAuth2](https://docs.feathersjs.com/api/authentication/oauth2.html) (and 1) for authentication through Google/Facebook/Twitter etc.

**Comment by uinz** [comment]
Yes, I think I should spend more patience in the documentation.

Thanks, I like `feathers`
