### ISSUE TITLE
Codetabs aren't rendering correctly on the services documentation page

### ISSUE THREAD

**Issue by sjsyrek** [feathersjs/docs#1011]
I tried to fix this, but I couldn't determine the problem. The syntax looks correct.

https://github.com/feathersjs/docs/blob/master/guides/basics/services.md

**Comment by daffl** [comment]
Which ones? They look fine in Chrome on Mac OS:

<img width="797" alt="screen shot 2018-01-04 at 8 38 47 am" src="https://user-images.githubusercontent.com/338316/34573933-bc8b8910-f12a-11e7-9ec1-dca4d9ebedd5.png">

**Comment by daffl** [comment]
Also just tested it on Firefox and Safari on Mac OS and am not seeing any issues.

**Comment by sjsyrek** [comment]
<img width="919" alt="feathers" src="https://user-images.githubusercontent.com/5577496/34604761-4fe445f6-f209-11e7-8d1e-b4e5a68d9c20.png">

Appears this way on my machine, macOS, both Chrome and Safari. The tags appear fine elsewhere in your docs, so this is indeed mystifying. Up to you if you want to pursue this.

**Comment by daffl** [comment]
They are not intended to work when reading it on GitHub. They will show up fine on the [rendered Services API page](https://docs.feathersjs.com/api/services.html) on [docs.feathersjs.com](https://docs.feathersjs.com).
