### ISSUE TITLE
Is it possible to provide an static parameter in url?

### ISSUE THREAD

**Issue by judicapo** [feathersjs/docs#1035]
Hello I am trying to reach this case of use, this is a multi Tennant app so when a user is logged it need to by identified as part of a company and all its action needs to be tracked with a companyId.

Is it possible to always send this companyId via socket up?

**Comment by daffl** [comment]
Add a `companyId` to your users. When a request is authenticated you can then use `params.user.companyId`.

**Comment by daffl** [comment]
To always restrict `companyId` a simple [hook](https://docs.feathersjs.com/api/hooks.html) can be used:

```js
app.service('messages').hooks({
  async before(context) {
    const { user } = context.params;

    if(context.id) {
      // For individual requests check if the user is allowed access (in the same company
      const data = await context.service.get(context.id, context.params);

      if(data.companyId !== user.companyId) {
        throw new Error('You are not allowed to access this');
      }
    } else {
      // Otherwise limit the query to the companyId
      context.params.query.companyId = user.companyId;
    }

    return context;
  }
});
```

**Comment by judicapo** [comment]
thank you.

 can this a solution apply for a user than would be part of more than one company at time?

**Comment by daffl** [comment]
Of course, just change the single check to `user.companyIds.includes(data.companyId)` and the query to `context.params.query.companyId = { $in: user.companyIds }`

**Comment by judicapo** [comment]
Cool, thank you.

**Comment by roelvan** [comment]
@daffl I get an infinite loop due to this line that is calling it's own hook again: `const data = await context.service.get(context.id, context.params);`. Do I need to add a `iff(isProvider('external'))` hook?

**Comment by daffl** [comment]
Ah yes, that would be one option. Another one would be to pass a flag to prevent recursive calls.

```js
app.service('messages').hooks({
  async before(context) {
    const { user, fromRestrict = false } = context.params;
    
    if(fromRestrict) { // If called recursively, skip it
      return context;
    }

    if(context.id) {
      // For individual external requests check if the user is allowed access (in the same company
      const data = await context.service.get(context.id, Object.assign({ fromRestrict: true }, context.params));

      if(data.companyId !== user.companyId) {
        throw new Error('You are not allowed to access this');
      }
    } else {
      // Otherwise limit the query to the companyId
      context.params.query.companyId = user.companyId;
    }

    return context;
  }
});
```
