### ISSUE TITLE
feathers-nedb-fuzzy-search broken link on doc

### ISSUE THREAD

**Issue by barata0** [feathersjs/docs#1055]
Hi,

The link to feathers-nedb-fuzzy-search on the botton of the page 
[https://github.com/feathersjs/docs/blob/master/api/databases/querying.md](https://github.com/feathersjs/docs/blob/master/api/databases/querying.md)

is wrong

It should link to 
[https://www.npmjs.com/package/feathers-nedb-fuzzy-search](https://www.npmjs.com/package/feathers-nedb-fuzzy-search)

But is linking to
[https://www.npmjs.com/package](https://www.npmjs.com/package)

**Comment by daffl** [comment]
Pull requests can be submitted by editing the page directly at https://github.com/feathersjs/docs/edit/master/api/databases/querying.md
