### ISSUE TITLE
Comment: Writing tests (guides/chat/testing.md)

### ISSUE THREAD

**Issue by cormacmcs** [feathersjs/docs#1056]
[package.json][scripts]
There is a problem on windows when setting the NODE_ENV as it does not work the same.
It needs to be "SET NODE_ENV=test".
With this though there is the issue that any trailing whitespace after the environment will be included so an '&' needs to be added right after 'test'. 
eg. ("mocha": "npm run clean & SET NODE_ENV=test& mocha test/ --recursive --exit")

**Comment by daffl** [comment]
Thank you! I added the note how the commands should look like for Windows.
