### ISSUE TITLE
Express Example 

### ISSUE THREAD

**Issue by oussamaABID** [feathersjs/docs#1064]
in the section sub app
https://docs.feathersjs.com/api/express.html#sub-apps

```js
const mainApp = express().use('/api', api);
```

```js
Error: @feathersjs/express requires a valid Feathers application instance
    at feathersExpress (@feathersjs\express\lib\index.js:11:11)
  
```
fix: 
```js
const mainApp = express(feathers()).use('/api/v1', api);
```

**Comment by daffl** [comment]
The example requires the latest version of `@feathersjs/express`. Make sure you have `v1.2.0` or later installed (`npm ls @feathersjs/express`).

**Comment by oussamaABID** [comment]
exactly my version  `1.1.2`
