### ISSUE TITLE
Comment: Primus (api/client/primus.md)

### ISSUE THREAD

**Issue by anselms** [feathersjs/docs#1072]
I think there's a bug in the primus client example: The following code from the docs fails, as "primus" is not defined. 

```
const feathers = require('@feathersjs/feathers');
const Primus = require('@feathersjs/primus-client');
const socket = new Primus('http://api.my-feathers-server.com');

const app = feathers();

app.configure(primus(socket));

// Receive real-time events through Primus
app.service('messages')
  .on('created', message => console.log('New message created', message));

// Call the `messages` service
app.service('messages').create({
  text: 'A message from a REST client'
});
```

I made it work, but wonder whether there is a more concise way than this:
```
const feathers = require("@feathersjs/feathers");
const primus = require("@feathersjs/primus-client");
const Emitter = require("primus-emitter");
const Primus = require("primus");

   // set up feathers client
    const Socket = Primus.createSocket({
      transformer: "websockets",
      plugin: {
        emitter: Emitter
      }
    });

    
    const socket = new Socket("http://localhost:3001", {
      transport: {
        headers: { cookie: sessionCookie}
      }
    });
    client = feathers();
    client.configure(primus(socket));
```

**Comment by daffl** [comment]
That's how Primus is initialized, what would you want to be more concise?

But yes, it needs the `@feathersjs/primus-client` import. An pull request to change that would be very welcome, the page can be edited at https://github.com/feathersjs/docs/edit/master/api/client/primus.md

**Comment by anselms** [comment]
Fair enough, if that is the primus api.

I'd be happy to correct the first sample, but it's more than just a missing import I suspect: I could not find any way to make it work. Using ` new Primus("http://localhost:3001")` just leads to "Error: Can not call 'on' on the client service connection" errors from feathers.

**Comment by daffl** [comment]
I think I fixed the code example, I'm pretty sure it was just a typo but I made the variable naming more clear anyway.
