### ISSUE TITLE
Comment: Processing data (guides/chat/processing.md)

### ISSUE THREAD

**Issue by kodayashi** [feathersjs/docs#1082]
It's not obvious to me how the the user._id param is present in the in the request to create a message. In the frontend section, I don't see where a user object (with an "_id") is injected into the network request to create a message. The code just shows the "text" value being created:

``    // Create a new message and then clear the input field
    await client.service('messages').create({
      text: input.value
    });``

Where is the user param being set that allows the server to extract the user's "_id"? Does the feathers client do this magically by decoding the JWT or something? Probably missing something simple here but I can't seem to figure it out.

**Comment by daffl** [comment]
This is mentioned in the previous chapter ([Adding authentication](ps://docs.feathersjs.com/guides/chat/authentication.html)) in the [Securing the messages service](https://docs.feathersjs.com/guides/chat/authentication.html#securing-the-messages-service) section:

> This will now only allow users with a valid JWT to access the service and automatically set params.user.

**Comment by kodayashi** [comment]
Wow thanks for the quick reply. Cool I went back and found that, but was confused b/c the userId in my postgres DB was set to null when trying to create a new message with a valid JWT. Decoding the JWT reveals the issue I think:

``{
 userId: 1,
 iat: 1518995062,
 exp: 1519081462,
 aud: "https://yourdomain.com",
 iss: "feathers",
 sub: "anonymous",
 jti: "542cfe1d-a755-4b89-9b5c-982bf73a0e47"
}``

The user's id is set as userId instead of _id, so the process-message hook isn't getting the value here. I'm not quite sure why the JWT gives me userId instead of _id, I'll investigate that.

**Comment by daffl** [comment]
Yes, that's the property that is being used by `authenticate('jwt')` hook to retrieve the actual user from the database (`users` service) and set that as `params.user`.

**Comment by kodayashi** [comment]
Ah, figured it out. Using knex and postgres, the user object being set had a prop of `id` not `_id`. I changed `userId: user._id,` to `userId: user.id,` and it worked fine. Probably just a difference in default behavior for postgres vs nedb (I was attempting the example using a different DB).

All set, thanks again for the reply!
