### ISSUE TITLE
Docs reference HS512 as the default algorithm for JWT, seems to be HS256

### ISSUE THREAD

**Issue by rafamel** [feathersjs/docs#1086]
### Docs reference HS512 as the default algorithm for JWT, seems to be HS256

Unsure whether is an error in the docs.

cli: 3.6.1
@feathersjs/feathers: 3.1.3
@feathersjs/authentication: 2.1.2

**Comment by daffl** [comment]
Good point, looks like it's definitely set to HS256 in https://github.com/feathersjs/authentication/blob/master/lib/options.js#L21 so a PR to fix the docs would be great.
