### ISSUE TITLE
Comment: JWT (api/authentication/jwt.md)

### ISSUE THREAD

**Issue by arifNislam** [feathersjs/docs#1090]
### Comment/Problem

Cannot authenticate another service (let's say, "playlists") hooks. hooks of that service is exported from another file. I am getting authorization token or passport object, but unable to authenticate in `before:{ create: [] }` hooks 

I am using `@feathersjs/authentication` and `@feathersjs/authentication-jwt`

**Comment by daffl** [comment]
Do you have a complete example? I'm not sure I understand.

**Comment by daffl** [comment]
Closing since the issue has been open for a while without any new information. Please feel free to reopen with more information at any time 😄
