### ISSUE TITLE
No auth token error after server restart

### ISSUE THREAD

**Issue by akucheruk-vareger** [feathersjs/docs#1092]
Hello,

I have a service /balances on the server with authentication turned on (jwt).
And a react web app with authentication-client and socket-io transport.

```
const socket = io(host);

const app = feathersClient()
    .configure(feathersClient.hooks())
    .configure(feathersClient.socketio(socket, { timeout: 30000 }))
    .configure(feathers.authentication({
      storage: window.localStorage
    }));
```

I'm use 'local' strategy to call authenticate() with login/password from login page and then get /balances every 10 seconds.

I have read about re-authenticating but after server restart I get No auth token error for /balances service every 10 seconds poll.

How I can handle server restart event and do re-authentication or how use re-authenticating properly?
May be there are way to know is we are authenticated, smth like isAuthenticated() before /balances poll and if not do authenticate() (with jwt stored already).
Or may be we can set an option(or get info about service from server) on the client for services that require authentication and handle this client-side, not even send request if we are not authenticated.

**Comment by daffl** [comment]
This issue is being tracked in https://github.com/feathersjs/feathers/issues/892
