### ISSUE TITLE
Comment: Configuration (api/configuration.md)

### ISSUE THREAD

**Issue by chadwithuhc** [feathersjs/docs#1095]
### Comment/Problem

Howdy! I couldn't find any information on how to load my own environment variables, so I used my normal `require('dotenv').config()` to get them loaded.

Is there an official way to do this through feathers instead?

**Comment by daffl** [comment]
The configuration module allows to pull in environment variables through placeholders in your configuration. E.g.

```js
{
  "mongodb": "MONGODB_URI"
}
```

Will look for the `MONGODB_URI` environment variable. There's also nothing wrong with loading your own dotenv. You can use [app.set](https://docs.feathersjs.com/api/application.html#setname-value) to load it into the Feathers application:

```js
app.set('dotenv', require('dotenv').config())
```

**Comment by chadwithuhc** [comment]
I know it's looking for the variables, but it doesn't load them when I'm local. I thought maybe feathers had something to actually load the environment variables.

**Comment by daffl** [comment]
Normal environment variables don't really to be loaded. They either exist in `process.env` or not.

If you want to use `dotenv` with Feathers, there is no hidden magic. It is the same [as using it anywhere else](https://github.com/motdotla/dotenv#usage), which is by running `require('dotenv').config()` (before loading the configuration module) or running your app with `node -r dotenv/config src/`.

**Comment by chadwithuhc** [comment]
OK, I'll stick with my `require('dotenv').config()` solution. Thanks!
