### ISSUE TITLE
Comment: Server (api/authentication/server.md)

### ISSUE THREAD

**Issue by dcsan** [feathersjs/docs#1097]
### Comment/Problem
this shows how to setup the server side but no example of how to call that code and authenticate properly.

how do I pass in a JWT token on an API request? 
any recommended method to enable a client to connect?
how to get the JWT token safely from server to client the first time?

**Comment by daffl** [comment]
This is documented in the [authentication client API](https://docs.feathersjs.com/api/authentication/client.html) and for direct usage in the [REST API](https://docs.feathersjs.com/api/client/rest.html#authentication) and [Socket.io](https://docs.feathersjs.com/api/client/socketio.html#authentication) sections.

**Comment by dcsan** [comment]
I searched a while and couldn't find it so thanks.
