### ISSUE TITLE
Comment: Configuration (api/configuration.md)

### ISSUE THREAD

**Issue by Aelbannan** [feathersjs/docs#1100]
### Comment/Problem

I'm sure this is very simple, but how do I get feathersjs to use config/production.json instead of config/default.json ?

**Comment by daffl** [comment]
Set the `NODE_ENV` environment to `production` as shown at the bottom of the [example in the documentation](https://docs.feathersjs.com/api/configuration.html#example).

**Comment by Aelbannan** [comment]
Awesome, thank you.
