### ISSUE TITLE
SSL certificate on docs site has expired

### ISSUE THREAD

**Issue by aral** [feathersjs/docs#1107]
https://www.ssllabs.com/ssltest/analyze.html?d=docs.feathersjs.com&latest

CC @daffl

**Comment by daffl** [comment]
Looks like something went wrong with Netlify regenerating the Letsencrypt certificate. Recreating the site with a new certificate fixed it. Hopefully we won't have this problem again in three months 😉

**Comment by gerwintown** [comment]
Doc sit for Auk release fails:
>The owner of auk.docs.feathersjs.com has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.

>This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.

This was fine just a few days ago.

**Comment by marshallswain** [comment]
I'm not having any issues loading in Firefox

**Comment by daffl** [comment]
That URL is fixed now as well thanks to the fantastic Netlify support. The better alternative would always be to [upgrade to the latest version](https://docs.feathersjs.com/migrating.html) though 😉
