### ISSUE TITLE
Comment: Security (SECURITY.md)

### ISSUE THREAD

**Issue by chadwithuhc** [feathersjs/docs#1121]
### Comment/Problem

The link to "filters" is pointing to http://docs.feathersjs.com/real-time/filtering.html but when following link I get redirected to https://docs.feathersjs.com/api/events.html

Not sure if there is a way to achieve this with Events which is why we get redirected there.

**Comment by daffl** [comment]
You were right, that section needed to be updated for the latest version. Thanks!
