### ISSUE TITLE
Comment: Processing data (guides/chat/processing.md)

### ISSUE THREAD

**Issue by silkcom** [feathersjs/docs#1127]
### Comment/Problem

While running feathers generate hook the final option to update the messages.hooks.js file is no longer available.

`
$ feathers generate hook
? What is the name of the hook? populate-user
? What kind of hook should it be? after
? What service(s) should this hook be for (select none to add it yourself)?
 
identical src/hooks/populate-user.js
identical test/hooks/populate-user.test.js
`

**Comment by daffl** [comment]
This usually happens if you don't select a service. You select a service by navigating to it with the arrow keys and pressing space.

**Comment by silkcom** [comment]
Interesting.  I was hitting enter

**Comment by daffl** [comment]
It's briefly mentioned at the beginning in

> Navigate to the entry with the arrow keys and select it with the space key.

If you do it'll work 😄
