### ISSUE TITLE
Docs site does not available in Russia

### ISSUE THREAD

**Issue by sxwebdev** [feathersjs/docs#1144]
The Russian government blocked a new list of ip-addresses. This list contains `18.184.7.177,` which is used by `docs.feathersjs.com`. The documentation is now unavailable in Russia. You can check this on the RKN website http://blocklist.rkn.gov.ru/#anchor

**Comment by sxwebdev** [comment]
![image](https://user-images.githubusercontent.com/3129246/40246514-aeb3d412-5ad1-11e8-9027-5a70b673a277.png)

This means that the provider of this VPN service has not yet updated the lists. My Internet provider in Moscow has already blocked the site docs.feathersjs.com

![image](https://user-images.githubusercontent.com/3129246/40246617-0ea4b2f6-5ad2-11e8-94ec-5b10c569b05a.png)

**Comment by sxwebdev** [comment]
In Russia, ROSKOMNADZOR does not block a specific IP address, but a whole subnet. Unfortunately there was a site with the documentation.

**Comment by daffl** [comment]
I will contact Netlify support to see if they can do anything. I also updated [the PDF](https://github.com/feathersjs/docs/blob/master/feathersjs.pdf) that can be used as a fallback.

**Comment by sxwebdev** [comment]
thanks for the fast feedback!

**Comment by daffl** [comment]
I notified Netlify about the problem and they were aware of it and are looking into it. Not much else we can do at the moment but I'll update the issue when I hear back.

**Comment by daffl** [comment]
This issue should now be fixed. Shout out to Netlify for being super helpful with this!

**Comment by sxwebdev** [comment]
Thank you! Now everything is working fine!

**Comment by ilyaigpetrov** [comment]
Sorry for the double-messaging.  
Netlify is partly blocked again in Russia: https://reestr.rublacklist.net/rec/565556/ (167.99.0.0/16).  
I have sent a message to Netlify.  
Sometimes https://docs.feathersjs.com opens just fine however, due to a load balancing I guess (the reason of my double-messaging).
