### ISSUE TITLE
Comment: Writing tests (guides/chat/testing.md)

### ISSUE THREAD

**Issue by DougFlemingAED** [feathersjs/docs#1152]
### Comment/Problem

I'm running through the chat example, having problems with my mocha tests. If I run:

```bash
npm run clean && NODE_ENV=test mocha test/services/users.test.js --exit
```

All tests pass in the users.test.js module, no problem.

If I attempt to run all tests recursivley:

```bash
npm run clean && NODE_ENV=test mocha test/ --recursive --exit
```

I get an error:

```bash
1) 'users' service
       creates a user, encrypts the password and adds a gravatar url:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (.../feathers-chat/test/services/users.test.js)
```

I found a similar issue about recursive tests failing with individual tests passing through google search [here](https://stackoverflow.com/questions/28845707/mocha-js-recursive-tests-fail-but-fine-as-individuals)

However I can't seem to figure out how or why I might be having clashing. I am using mongoDB with mongoose for this example.

If I comment out all of my user service test code, recursive testing is fine, so I figure it must be something to do with calling the user service.create method in conjuction with running all tests at the same time.

If I comment out the assertions and the line which calls the service.create method, in this users service test suite, recursive tests are fine, as soon as that line is run the error happens. Test 1 'registered the service' runs fine for both individual and recursive testing.

Users service test code:

```javascript
const assert = require('assert');
const app = require('../../src/app');

describe('\'users\' service', () => {

  it('registered the service', () => {
    assert.ok(app.service('users'), 'Service not registered...');
  });

  it('creates a user, encrypts the password and adds a gravatar url', async () => {
    const email = 'test@example.com';
    const password = 'password';

    const user = await app.service('users').create({ email, password });

    assert.ok(user);
    assert.equal(email, user.email);

    assert.equal(user.avatar, 'https://s.gravatar.com/avatar/55502f40dc8b7c769880b10874abc9d0?s=60');
    assert.ok(user.password != password);
  });
});
```

### System configuration

**Module versions**
package.json
```json
{
  "name": "feathers-chat",
  "description": "a feathers tutorial",
  "version": "0.0.0",
  "homepage": "",
  "main": "src",
  "keywords": [
    "feathers"
  ],
  "author": {
    "name": "Doug",
    "email": "..."
  },
  "contributors": [],
  "bugs": {},
  "directories": {
    "lib": "src",
    "test": "test/"
  },
  "engines": {
    "node": "^9.0.0",
    "npm": ">= 3.0.0"
  },
  "scripts": {
    "test": "npm run eslint && npm run mocha",
    "eslint": "eslint src/. test/. --config .eslintrc.json",
    "start": "node src/",
    "clean": "NODE_ENV=test node test/test-database-clean",
    "mocha": "npm run clean && NODE_ENV=test mocha test/ --recursive --exit"
  },
  "dependencies": {
    "@feathersjs/authentication": "^2.1.5",
    "@feathersjs/authentication-jwt": "^2.0.1",
    "@feathersjs/authentication-local": "^1.2.1",
    "@feathersjs/configuration": "^1.0.2",
    "@feathersjs/errors": "^3.3.0",
    "@feathersjs/express": "^1.2.2",
    "@feathersjs/feathers": "^3.1.5",
    "@feathersjs/socketio": "^3.2.1",
    "compression": "^1.7.2",
    "cors": "^2.8.4",
    "feathers-mongoose": "^6.1.1",
    "helmet": "^3.12.1",
    "mongoose": "^5.1.1",
    "serve-favicon": "^2.5.0",
    "winston": "^2.4.2"
  },
  "devDependencies": {
    "eslint": "^4.19.1",
    "feathers-memory": "^2.1.1",
    "mocha": "^5.2.0",
    "request": "^2.86.0",
    "request-promise": "^4.2.2"
  }
}

```

**NodeJS version**:
V9.4.0

**Operating System**:
macOS High Sierra 10.13.4

**Comment by daffl** [comment]
Are there any differences to the chat repository at https://github.com/feathersjs/feathers-chat ? I just tested it there and I am not seeing the problem.

**Comment by DougFlemingAED** [comment]
The main difference is I'm using mongoose with mongodb in my version. I tried switching the model and service over to the 'nedb' version as per your repo and recursive tests are running fine, no problems at all.

My model and service using mongoose:

Model
```javascript
// users-model.js - A mongoose model
//
// See http://mongoosejs.com/docs/models.html
// for more of what you can do here.
module.exports = function (app) {
  const mongooseClient = app.get('mongooseClient');
  const users = new mongooseClient.Schema({
  
    email: {type: String, unique: true, required: true},
    password: { type: String, required: true },
    avatar: { type: String }
  
  }, {
    timestamps: true
  });

  return mongooseClient.model('users', users);
};
```

Service
```javascript
// // Initializes the `users` service on path `/users`
// const createService = require('feathers-mongoose');
// const createModel = require('../../models/users.model');
// const hooks = require('./users.hooks');

module.exports = function (app) {
  const Model = createModel(app);
  const paginate = app.get('paginate');

  const options = {
    Model,
    paginate
  };

  // Initialize our service with any options it requires
  app.use('/users', createService(options));

  // Get our initialized service so that we can register hooks and filters
  const service = app.service('users');

  service.hooks(hooks);
};
```

The .create method in 'feathers-mongoose' is different to the one in 'feathers-nedb' of course, but with tests passing when running just the 'users.test.js' module I'm not sure there is any issue there.

I pushed up my code to [this](https://github.com/DougFlemingAED/feathers-chat-testing) (temporary) repo just in case there is anything else you would want to look at. It'd be interesting to see if you can replicate the issue with my version. I left in the commented out code I used to switch over to 'nedb'

I've been running a local mongodb server with docker.
```bash
doug$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
47282ee5f0cf        mongo               "docker-entrypoint.s…"   2 days ago          Up About an hour    0.0.0.0:27017->27017/tcp   mongo-instance
```

**Comment by DougFlemingAED** [comment]
I tried 'jest' instead of 'mocha', and recursive tests are passing.

**Comment by daffl** [comment]
I was just looking into this and it's pretty wild. Basically everything works fine when you run the app normally (and you can also run the same code as in the tests and it will work) but as soon as you run it in Mocha (even with the exact same options) Mongoose just ends up doing nothing. No error messages, no timeouts, just nothing.

**Comment by DougFlemingAED** [comment]
Yes very strange! I'm glad you could replicate. Thank you for taking the time to check it out, I appreciate it.

**Comment by DougFlemingAED** [comment]
Jasmine works fine too for recursive tests

**Comment by iva2k** [comment]
Mocha is sensitive to arrow vs. function in the describe() call, per [this answer on SO](https://stackoverflow.com/questions/16607039/in-mocha-testing-while-calling-asynchronous-function-how-to-avoid-the-timeout-er/46392720#46392720).

To fix this sporadic timeout error in feathersjs, in /test/app.test.js change this line:
`describe('Feathers application tests', () => {`
to this:
`describe('Feathers application tests', function() {`

It solved the error for me.
