### ISSUE TITLE
Comment: Channels (api/channels.md)

### ISSUE THREAD

**Issue by TitoVince35** [feathersjs/docs#1154]
### Deleting channels
What about unused, empty channels?

My app's channels can multiply very fast, keeping less than 10 connections and getting useless at the end of a brief session. I haven't noticed any method to delete a channel.
Even though a channel's footprint may be as small as its name, this is bothering me. I have created a service to track connections/channels and it just displays too many useless channels!

What do you think?

Thank you.

**Comment by daffl** [comment]
Clearing them out wouldn't be that hard (you have to import the Symbol that is used as the key though):

```js
const { keys } = require('@feathersjs/transport-commons').channels;
const { CHANNELS } = keys;

app.channels.forEach(name => {
  if(app.channel(name).length === 0) {
    delete app[CHANNELS][name];
  }
});
```

The challenge is when to run this. Technically every time `.leave` is called but since a channel doesn't know about the `app` and the `app` can't easily hook into a `channel.leave` it's a little tricky.

**Comment by daffl** [comment]
I think it's a good point that empty channels should be deleted. I think I can make that happen by also turning the channel objects into event emitters and listening to an `empty` event on which it will be deleted from the `CHANNEL` object.

**Comment by TitoVince35** [comment]
Sounds great!
Is it something you plan to implement in Feathers core in a next future?

**Comment by daffl** [comment]
It turned out to be fairly simple actually. The pull request is at https://github.com/feathersjs/transport-commons/pull/75

**Comment by ssh713** [comment]
Hi, I have a question similar to this discussion: Is there any way or event that tells when a client is disconnected on socket from the server ? There is app.on('connection') event but is there any similar like app.on('disconnect'). I know there is a logout event but sometimes users will be offline for other reasons e.g. no internet
