### ISSUE TITLE
Comment: Socket.io (api/client/socketio.md)

### ISSUE THREAD

**Issue by altwohill** [feathersjs/docs#1157]
### Comment/Problem

How do we handle reconnecting the socket? ie after a react-native app has been backgrounded and then brought back, the socket seems to think that it is still connected but requests just time out.

**Comment by daffl** [comment]
Is this happening with the websocket configuration [recommended in the React Native usage documentation](https://docs.feathersjs.com/api/client.html#react-native)? Specifically

```js
const socket = io('http://api.my-feathers-server.com', {
  transports: ['websocket'],
  forceNew: true
});
```
