### ISSUE TITLE
Comment: Security (SECURITY.md)

### ISSUE THREAD

**Issue by frastlin** [feathersjs/docs#1158]
### Comment/Problem

There should be something that talks about setting up https for your server on this page.
The only place that seems to talk about FeathersJS is a [legacy article](https://legacy.docs.feathersjs.com/middleware/mounting.html).
When I google "HTTPS FeathersJS", [this support https article](https://github.com/feathersjs/feathers/issues/25) shows up. It makes me think that there is something beyond [what you need to do for Express](https://medium.com/@nileshsingh/everything-about-creating-an-https-server-using-node-js-2fc5c48a8d4e).
HTTPS is now pretty much standard and Firefox and Chrome won't allow a secured app to talk with an unsecured server. Setting up SSL with FeathersJS should be the guide you read right after the chat app, it's so important.

**Comment by daffl** [comment]
There is a complete example how to set up HTTPS [in the API documentation](https://docs.feathersjs.com/api/express.html#https).

**Comment by daffl** [comment]
Since there is documentation on how to set up HTTPS and what I already mentioned in #1156 I'm going to close this issue. We can discuss further in #1156 😄
