### ISSUE TITLE
Comment: Configuration (api/configuration.md)

### ISSUE THREAD

**Issue by AndrewJDR** [feathersjs/docs#1160]
It would be great if this page expanded more upon this statement:
> Also try to load <NODE_ENV>.json in that path, and if found, *extend the default configuration*

In particular, the "extend the default configuration" portion. How does that work if there are two objects with the same key, do they get merged together, or is one just replaced with the other?
i.e. if default.json has:
```
"someConfig": {
"keyOne": 5,
"keyTwo": 7
}
```

and production.json has:
```
"someConfig": {
"keyOne": 8,
"keyThree": 9
}
```

Do we end up with (merge)?
```
"someConfig": {
"keyOne": 8,
"keyTwo": 7,
"keyThree": 9
}
```

Or this (replace):
```
"someConfig": {
"keyOne": 8,
"keyThree": 9
}
```

And what if the objects/arrays are deeply nested, will those be deeply merged, or is replacement eventually used at some level of depth?

**Comment by daffl** [comment]
As mentioned in the beginning of the pages, this is just a wrapper of [node-config](https://github.com/lorenwest/node-config) whose readme and [documentation](https://github.com/lorenwest/node-config/wiki) shows that they are merged recursively. A pull request adding a section on expanding configuration values before the `Changing the location of the configuration directory` section would be welcome.
