### ISSUE TITLE
Comment: Services (api/services.md)

### ISSUE THREAD

**Issue by compwright** [feathersjs/docs#1166]
### Comment/Problem

.mixin() does not exist on services (at least not feathersjs-mongoose). However, .extend() does exist and it appears per https://github.com/feathersjs-ecosystem/feathers-mongoose/issues/12 that the proper syntax is to call .extend() to get a service that has the .mixin() method.

### System configuration (optional)

**Module versions** (especially the part that's not working):

* @feathersjs/feathers: 3.1.7
* feathers-mongoose: 6.1.2

**NodeJS version**: 8 LTS

**Comment by daffl** [comment]
`.mixin` should always exist when using the service object returned by [app.service(path)](https://docs.feathersjs.com/api/application.html#servicepath).
