### ISSUE TITLE
Comment: Errors (api/errors.md)

### ISSUE THREAD

**Issue by bgold0** [feathersjs/docs#1170]
### Comment/Problem

Any new error is always giving a 200 status from any example that you give. It's not clear on how to get the appropriate status code that you have listed out on the examples page.

**Comment by daffl** [comment]
Which examples do you mean? With a normal setup (including the [Express error handler](https://docs.feathersjs.com/api/express.html#expresserrorhandler)) the proper error codes will be set automatically for any error that is thrown.

**Comment by bgold0** [comment]
@daffl that's not the case for me. 

For example, if I do:

    const errors = require('@feathersjs/errors');
    const notFound = new errors.NotFound('User does not exist');
    return notFound;

I get a 200 status coming back.
