### ISSUE TITLE
Comment: Processing data (guides/chat/processing.md)

### ISSUE THREAD

**Issue by Strongbyte-ES** [feathersjs/docs#1181]
I found I had old test messages in the NeDB database which then caused the hook to error with the following error message since `message.userId` is `undefined` in that case.
```
error: Error: An id must be provided to the 'get' method
```
One solution to avoid that is the following defensive `messages.filter`
```javascript
    // Asynchronously get user object from each message's `userId`
    // and add it to the message
    await Promise.all(messages
      .filter(message => message.userId) // Defensively exclude any messages without `userId`
      .map(async message => {
      // Also pass the original `params` to the service call
      // so that it has the same information available (e.g. who is requesting it)
      message.user = await app.service('users').get(message.userId, params);
    }));
```
However it is probably best to throw an error to advise the reader to clear the NeDB database i.e. remove the `data` folder and restart the app.

**Comment by daffl** [comment]
This is already mentioned right at the beginning of the [Processing data](https://docs.feathersjs.com/guides/chat/processing.html) section:

>  For this chapter we require an empty database which can be done by removing the data/ folder (rm -rf data/).

**Comment by Strongbyte-ES** [comment]
Ah sorry i missed that ;)
