### ISSUE TITLE
Comment: Adding authentication (guides/chat/authentication.md)

### ISSUE THREAD

**Issue by vrsttl** [feathersjs/docs#1188]
### Comment/Problem
pasted in

`const { authenticate } = require('@feathersjs/authentication').hooks;`

into messages.hooks.js.

I did follow the tutorial word by word, line by line, except I added a nodemon dev dependency to package.json to auto-restart on save.

Error: Cannot find module '@feathersjs/authentication'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\vrstt\Documents\greenfox\vrsttl\Week-10\feathers-practice\src\services\messages\messages.hooks.js:1:88)

### System configuration (optional)

Dell Vostro i3 chip, 8gbDDR$ RAM, Win10 64bit, VSCode

**Module versions** (especially the part that's not working):
+ feathers-authentication-hooks@0.3.0
+ feathers-authentication@1.3.1
+ feathers-authentication-local@0.4.4
+ feathers-authentication-jwt@0.3.2

**NodeJS version**:
v8.11.1
**Operating System**:
Win10 64bit
**Browser Version**:
Chrome 68.0.3440.84 64bit
**React Native Version**:
none
**Module Loader**:
require

**Comment by daffl** [comment]
If `@feathersjs/authentication` is included in your `package.json` `dependencies`, running `npm install` will probably solve the problem.

**Comment by vrsttl** [comment]
I restarted the whole project from the beginning and now it works. Thanks!
