### ISSUE TITLE
Comment: Recipe: Basic OAuth (guides/auth/recipe.oauth-basic.md)

### ISSUE THREAD

**Issue by tconroy** [feathersjs/docs#1189]
### Comment/Problem

Following the exact steps as outlined in the oauth basic guide, the `users` table does not seem to be created. When GitHub redirects with the token, the app errors with:

```
error: SequelizeDatabaseError: relation "users" does not exist
```

Tell us about the applicable parts of your setup.

**Module versions**
```
    "@feathersjs/authentication": "^2.1.7",
    "@feathersjs/authentication-jwt": "^2.0.1",
    "@feathersjs/authentication-local": "^1.2.1",
    "@feathersjs/authentication-oauth2": "^1.1.0",
    "@feathersjs/configuration": "^2.0.0",
    "@feathersjs/errors": "^3.3.0",
    "@feathersjs/express": "^1.2.3",
    "@feathersjs/feathers": "^3.1.7",
    "@feathersjs/socketio": "^3.2.2",
    "feathers-sequelize": "^3.1.2",
    "passport-github": "^1.1.0",
    "pg": "^7.4.3",
    "pg-hstore": "^2.3.2",
    "sequelize": "^4.38.0",
```

**NodeJS version**:
v8.9.1

**Operating System**:
MacOS

**Browser Version**:
Chrome Latest

**Module Loader**:

**Comment by daffl** [comment]
For relational databases, the oAuth response has to be modified according to the user model schema. This is documented in https://docs.feathersjs.com/api/authentication/oauth2.html#customizing-the-oauth-response
