### ISSUE TITLE
Join a channel before publish on create

### ISSUE THREAD

**Issue by ZeroSoulEater** [feathersjs/docs#1191]
Hey I would like to know what is the best practice for my problem,

for example in a chat app, after a chat is created I need to join all users the channel `chats/${chat.id}`. After they joined the clients need to get the on created signal.

If I use the `channels.js` (see below) the user will join the channel after the on created is published to to the channel. So no one will get notified.

```
app.service('chats').on('created', chat => {
    …
   updateChannels(user);
  });
```

If I use a after create hook I don't have access to `chat.id` and can't let the users join the channel `chats/${chat.id}`.

Maybe you can help me and provide an example in the documentation. 😄

**Comment by daffl** [comment]
You can use [params.connection](https://docs.feathersjs.com/api/socketio.html#paramsconnection) to join the channel in an `after` hook which will happen before the event is sent:

```js
app.service('chats').hooks({
  after: {
    create(context) {
      const chat = context.result;

      context.app.channel(`chats/${chat.id}`).join(context.params.connection);

      return context;
    }
  }
});
```

**Comment by ZeroSoulEater** [comment]
sorry had a few days off.

but why I have access to the id in

```
app.service('chats').hooks({
  after: {
    create(context) {
       …
     }
  }
})
```
but not in 

```
module.exports = {
  before: {
    all: [authenticate('jwt')],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  after: {
    all: [],
    find: [],
    get: [],
    create: [afterCreateChat],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};
```

**Comment by daffl** [comment]
It's [the same thing](https://docs.feathersjs.com/api/hooks.html#registering-hooks). `afterCreateChat` will also have `context.result` which is the newly created chat and `context.result.id` which is its id.

**Comment by ZeroSoulEater** [comment]
well you are right, sorry looks like I messed something up

**Comment by ZeroSoulEater** [comment]
sorry I have to ask one more question, if I start a chat I want to join every participant the channel.

I tried the code below, first get all connections from the participants and after this, let all connections join the channel for the chat. But my Clients are not receiving an created signal.
```
app.service('chats').hooks({
    after: {
      async create(context) {
        const { result } = context;
        const participants= result.participants;
        let conns=[];
        // Add participants to the channel for this chat before send the created signal
        for(let i=0; i<participants.length; i++){
          let {connections} = app.channel(app.channels).filter(connection =>
            connection.user.id === participants[i].id
          );
          conns.push(connections);
        }

        for(let i=0; i<conns.length;i++){
          await app.channel(`chats/${result.id}`).join(conns[i])
        }
        console.log('wut wut wut',JSON.stringify(app.channel(`chats/${result.id}`)));

        app.service('chats').publish('created', (data) => {
          return app.channel(`chats/${data.id}`);
        });

        return context;
      }
    }
  });
```
