### ISSUE TITLE
More detailed documentary on nested $select function in DB querying

### ISSUE THREAD

**Issue by simodrws** [feathersjs/docs#1206]
### Comment/Problem

Hey guys,

After fumbling around with the $select parameter in the querying syntax I found out that:

You can either use `$select: ['key1', 'key2']`

or

```
$select: { 
  key1: true,
  key2: true,
  key3: ['nestedKey1', 'nestedKey2'],
}
```

The second one is especially useful if you want to aggregate & dispatch results modularily. 

Save some fellow developers some time!

cheers,
s.

in here: https://docs.feathersjs.com/api/databases/querying.html#select

**Comment by simodrws** [comment]
Hey daffl,

I am working with the rethinkdb adapter but the person working on it is looking for someone new to maintain the project.

It is working for rethinkdb.

Maybe it would be good to have a solution to do nested selects for all adapters?

Cheers

**Comment by daffl** [comment]
Unfortunately this won't be possible for the SQL or filesystem/in-memory adapters so it probably makes sense to keep it adapter specific.
