### ISSUE TITLE
Question: Is it possible to change the route path for services to use singular naming convention? 

### ISSUE THREAD

**Issue by TheFoot** [feathersjs/docs#1219]
Hi..

We have a REST URL naming policy which stipulates that our APIs for collections are plural, and single resources - singular.

Can I configure feathers routes this way please?

E.g.: `/user/:id` not `/users/:id`

**Comment by daffl** [comment]
There is no convention around that in Feathers. A service will have the name you give it when registering it with `app.use`. You can change it at any time in the `*.service.js` file (and update the name used accordingly, e.g. in the authentication configuration).

**Comment by TheFoot** [comment]
Thanks for responding so quickly. I wasnt clear sorry - I meant that by default feathers seems to use the plural for both collection and single resource paths - can I change this so that the following are supported for a "users" service for example?

```
GET /users - search
GET /user/:id - get one
DEL /user/:id - del one
...
```
