### ISSUE TITLE
Comment: Recipe: Express middleware (SSR) (guides/auth/recipe.express-middleware.md)

### ISSUE THREAD

**Issue by kennethlooney** [feathersjs/docs#1223]
### Comment/Proble
After filling in the login form with a valid user (verified through Postman) if I click the login button it does a post back and stays on the login page.
### System configuration (optional)

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:
v.11.0.0
**Operating System**:
Ubuntu 18.4
**Browser Version**:
Chrome Version 70.0.3538.77 (Official Build) (64-bit)
**React Native Version**:

**Module Loader**:
I used your CLI to create the app. (feathers g app)

**Comment by daffl** [comment]
Closing since this has changed significantly in v4
