### ISSUE TITLE
Comment: Scaling (guides/advanced/scaling.md)

### ISSUE THREAD

**Issue by willston77** [feathersjs/docs#1232]
### Comment/Problem

With the examples, can you do more to make them consistent with the generators scaffolding?  For instance, with the Scaling guide could you show how to scale a feathers app made with the feathers generator?

**Comment by eddyystop** [comment]
+1

**Comment by cantoute** [comment]
Actually I believe the documentation is leading into the wrong direction.

I tried what is suggested (node-custer), but when using socketio it comes to some really complex and dodgy setups.

On the other hand, firing several instances of your feather api then using feathers-sync https://github.com/feathersjs-ecosystem/feathers-sync to sync between your multiple nodes is far more simple and probably will survive better to futur updates.
