### ISSUE TITLE
Comment: Real-time APIs (guides/basics/real-time.md)

### ISSUE THREAD

**Issue by outluch** [feathersjs/docs#1233]
### Comment/Problem
I couldn't run tutorial at this point because of CORS problem with io connection. We start socketIO transport on 3030 port, but trying to connect to it from our public/client.js, served with http-server on 8080 port. CORS problem. I played with configuring socket io transport cors option but no luck. Didnt find in docs either.

**Comment by daffl** [comment]
It should not cause any problems unless Socket.io falls back to polling. Websockets do not have a CORS restriction but they may have to be forced during initialization on the client:

```js
// This should work
const socket = io('http://localhost:3030');
// If not, this will
const socket = io('http://localhost:3030', {  transports: ['websocket'] });
```
