### ISSUE TITLE
Comment: Generating a service (guides/chat/service.md)

### ISSUE THREAD

**Issue by DGZN** [feathersjs/docs#1240]
### Comment/Problem

The chat application documentation is broken. 
Feathers returns a 404 error on the /messages path

### System configuration 

**NodeJS version**:

v10.14.2

**Operating System**:

Windows 10

**Comment by daffl** [comment]
I tested it with Node 11+ and the `@feathersjs/cli@3.9.0` on Windows 10 and the chat guide works as expected. Try using the latest version and following the steps again.
