### ISSUE TITLE
Comment: Uploading files - Issue with websocket client

### ISSUE THREAD

**Issue by apmcodes** [feathersjs/docs#1241]
### Problem

This file uploading guide is using **Express Middleware** multer and a custom middleware function. 

However, if we use socketio provider in the frontend (like quasar with feathers socket client) then these 2 express middlewares do not run. In that case, how can we parse mutlipart file upload with feathersjs while using socket provider.

**Comment by apmcodes** [comment]
@daffl can you please clarify ... Thanks

**Comment by daffl** [comment]
This section shows a standard file upload via the browser. You'd have to implement file uploads via Socket.io yourself, maybe with something like the https://www.npmjs.com/package/socketio-file-upload plugin.

**Comment by apmcodes** [comment]
Thanks for your response. Can I use REST client along

**Comment by apmcodes** [comment]
Just for the file upload service, used Axios in the frontend. Manually added custom events in the upload service to communicate progress to frontend.

Thanks for the wonderful framework.
