### ISSUE TITLE
Possible to emit Custom events from Middilewares?

### ISSUE THREAD

**Issue by apmcodes** [feathersjs/docs#1242]
### Comment/Problem

Is it possible to emit Custom events from Middilewares? 
Possible to raise events from services, hooks, but nothing mentioned about middlewares. 

Please clarify.

**Comment by daffl** [comment]
Yes, [req.app](https://expressjs.com/en/4x/api.html#req.app) in a middleware is the application so you can do `req.app.service('myservice').emit('myevent')`.
