### ISSUE TITLE
Comment: Channels (api/channels.md)

### ISSUE THREAD

**Issue by MichaelJCole** [feathersjs/docs#1244]
https://docs.feathersjs.com/api/channels.html#channelfilterfn

This example has some important stuff going on that isn't explained:

```
// Returns a new channel with all connections of the user with `_id` 5
const userFive = app.channel(app.channels)
  .filter(connection => connection.user._id === 5);
```

User5 could have multiple connections (e.g. different browsers).

Also this looks like it's iterating all connections to the server.  Does this scale across web servers? 

I think this code:  `app.channel(app.channels)` makes one channel from all channels, then `.filter` returns a new channel with just user 5.  Is this the best practice to send a message to all user 5's connections?

**Comment by daffl** [comment]
Filtering is very fast (everything is in memory) so you will probably not notice a difference but the better way is to create one channel for user 5 and send to that since it will contain all connections for that user (in constant time). Filtering should ideally only be used for leaving channels
