### ISSUE TITLE
The Feathers Cookbook

### ISSUE THREAD

**Issue by daffl** [feathersjs/docs#1249]
The [crow documentation](https://crow.docs.feathersjs.com) has a new [Cookbook](https://crow.docs.feathersjs.com/cookbook/) section to collect Feathers recipes of common patterns and tips that can be useful.

I am hoping that this will help to get more community contributions for content. While it is great to get community contributions for e.g. new guides, it has always been a challenge to keep it up to date with the latest developments. A cookbook recipe will show when and for what version it has been written for. If it is more than two versions behind and hasn't been updated or verified to still work, it will be removed.

Please add a comment if you have ideas or things you would like to see in a Feathers cookbook.

**Comment by edwardsmarkf** [comment]
i am not on crow yet, but i would like to see this promoted more on slack.

Thank you,

Mark Edwards

**Comment by daffl** [comment]
Reopening to collect some of the ideas:

- Authentication
  - [ ] Anonymous Authentication
  - [ ] Token blacklisting
  - [ ] oAuth account linking
- Real-time
  - [ ] Marking users as offline/online
  - [ ] Channels for a specific client

**Comment by edwardsmarkf** [comment]
i would like to see a custom SQL statement using sequelize and feathersJS.
sequelize lets you use "raw sql" but i have not figured how that works in
feathers-sequelize yet.

also, i would like to see more detailed use of the channels with lots of
examples.

my project combined feathersJS with jqwidgets, and the results are amazing.

Thank you,

Mark Edwards

**Comment by edwardsmarkf** [comment]
another addition to a cookbook would be the way to extract out user login
information while using Oauth2.   when i first started out, a slack user
Freeline graciously helped me get this going:

const setUserInfo = (async (response) => {
            // a special thanks to feathers-slack "freeline" for providing
this code
        let payload     = await
feathersApp.passport.verifyJWT(response.accessToken);
        let user        = await
feathersApp.service('oauth-2-logins').get(payload.userId);
        feathersApp.set('user', user);  // feathersApp.get('user').email to
get email address
        console.log('you logged in as: ' + feathersApp.get('user').email
    ); // display what is now in user in the console.
        selectedTeacherEmail = feathersApp.get('user').email;
        selectedDisplayName = feathersApp.get('user').displayName;
})





Thank you,

Mark Edwards


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by daffl** [comment]
This has been done. New Cookbook suggestions can be added in the [Feathers discussions](https://github.com/feathersjs/feathers/discussions).
