### ISSUE TITLE
Comment: Building a frontend (guides/chat/frontend.md)

### ISSUE THREAD

**Issue by ngothean** [feathersjs/docs#1252]
### front end - chat application 
https://docs.feathersjs.com/guides/chat
I follow the tutorial step by step. Everything is fine until the front end. At first I got this error when launch localhost:8080 in the browser
 "GET /socket.io/socket.io.js" Error (404): "Not found"
So, I create the folder 
public/socket.io
and copy the file socket.io.js from node_modules/socket.io-client/dist/socket.io.js there
Then, the login screen shows up, but doesn't work. 
Error "POST /socket.io/?EIO=3&transport=polling&t=MXPyj2l" Error (404): "Not found"

### System configuration (optional)
Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**: 8.10.0

**Operating System**: Ubuntu 18.04.1 LTS 

**Browser Version**: Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**React Native Version**: 

**Module Loader**:

Thank you

**Comment by daffl** [comment]
The files should be created in the server folder, as the guide mentions:

> We are already serving the static files in the public folder and have a placeholder page in public/index.html

Then go to [http://localhost:3030](http://localhost:3030) not the other webserver that is running.

**Comment by ngothean** [comment]
Thank you Daffl
