### ISSUE TITLE
Comment: Querying (api/databases/querying.md)

### ISSUE THREAD

**Issue by rupeshbhurke** [feathersjs/docs#1257]
### Comment/Problem

I was trying out your code from `https://docs.feathersjs.com/guides/basics/databases.html#as-a-rest-api`
I added the following part of your createAndFind function with it.
```
async function createAndFind() {
    // Stores a reference to the messages service so we don't have to call it all the time
    const messages = app.service('messages');
    for(let counter = 0; counter < 100; counter++) {
        await messages.create({
            counter,
            message: `Message number ${counter}`
        });
    }
}
createAndFind();
```

The data was populated as expected and was showing with `http://localhost:3030/messages`
Result:
```
{
    "total": 100,
    "limit": 10,
    "skip": 0,
    "data": [
        {
            "counter": 0,
            "message": "Message number 0",
            "id": 0
        },
        {
            "counter": 1,
            "message": "Message number 1",
            "id": 1
        },
        {
            "counter": 2,
            "message": "Message number 2",
            "id": 2
        },
        {
            "counter": 3,
            "message": "Message number 3",
            "id": 3
        },
        {
            "counter": 4,
            "message": "Message number 4",
            "id": 4
        },
        {
            "counter": 5,
            "message": "Message number 5",
            "id": 5
        },
        {
            "counter": 6,
            "message": "Message number 6",
            "id": 6
        },
        {
            "counter": 7,
            "message": "Message number 7",
            "id": 7
        },
        {
            "counter": 8,
            "message": "Message number 8",
            "id": 8
        },
        {
            "counter": 9,
            "message": "Message number 9",
            "id": 9
        }
    ]
}

```
But when queried using the following query it does not return any records:

`localhost:3030/messages?counter=1`

Result

```
{
    "total": 0,
    "limit": 10,
    "skip": 0,
    "data": []
}
```

Why is this happening?

Kindly Guide!

### System configuration (optional)

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
@feathersjs/feathers 3.3.1

**NodeJS version**:
10.15.0

**Operating System**:
Windows 10 64 Bit

**Browser Version**:
Postman (Version latest as on the 29/Jan/2019)

**React Native Version**:
Not in use

**Module Loader**:
npm

**Comment by daffl** [comment]
This is mentioned in the beginning of the [querying API documentation](https://docs.feathersjs.com/api/databases/querying.html):

> __Important:__ When used via REST URLs all query values are strings. Depending on the service the values in params.query might have to be converted to the right type in a before hook.

**Comment by rupeshbhurke** [comment]
Could you please provide a sample code. If sample matches with what I am trying to do, even better!
