### ISSUE TITLE
Comment: Services (api/services.md)

### ISSUE THREAD

**Issue by ssh713** [feathersjs/docs#1260]
### Comment/Problem

I am trying to figure out how to customize a service for following scenarios
1) In find/get methods i want to add additional information which may be retrieved from calling a different service
2) If a user logs in, how can i call another service say to keep track of currently logged in users.

**Comment by daffl** [comment]
1. How to associate data is shown in the [chat application guide](https://docs.feathersjs.com/guides/chat/readme.html)
2. You can listen to the [`app.on('login')` event](https://docs.feathersjs.com/api/authentication/server.html#apponlogin-callback) and do anything you need (e.g. `patch`ing the user with `{ online: true }`) there.
