### ISSUE TITLE
Comment: Recipe: Basic OAuth (guides/auth/recipe.oauth-basic.md)

### ISSUE THREAD

**Issue by deskoh** [feathersjs/docs#1268]
### Comment/Problem

The sample code uses deprecated client library`//unpkg.com/feathers-client@2.0.0/dist/feathers.js`.

After updating to `//unpkg.com/@feathersjs/client@^3.0.0/dist/feathers.js`, `feathers.hooks` becomes undefined.

### System configuration (optional)

N.A.

**Module versions** (especially the part that's not working):

N.A.

**Comment by daffl** [comment]
oAuth will be quite different and properly documented in the upcoming Feathers v4. See the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information.
