### ISSUE TITLE
is there any app.on('disconnect') event ?

### ISSUE THREAD

**Issue by ssh713** [feathersjs/docs#1271]
### Comment

I am wondering if there is anything similar to app.on('disconnect', ) event. In the context of chat app how can we let participants know of someone who has disconnected ? There is logout event but there could be other scenarios e.g. loss of internet connection where other clients may want to know if a connection has become offline.

**Comment by daffl** [comment]
Duplicate of https://github.com/feathersjs/feathers/issues/1243
