### ISSUE TITLE
Comment: Express (api/express.md)

### ISSUE THREAD

**Issue by MichaelJCole** [feathersjs/docs#1274]
### Comment/Problem

This page says array, but then shows spread of parameters in example:

https://docs.feathersjs.com/api/express.html#appusepath-servicemwmw

app.use(path, service|mw|[mw]) -> app registers either a service object, an Express middleware or an array of Express middleware on the given path.

```
app.use('/test/', {});
app.use('/test/', ()=>{});
app.use('/test/', [()=>{}, ()=>{}]);
```
And the example:

```
// Register multiple Express middleware functions
app.use('/test', (req, res, next) => {
  res.data = 'Step 1 worked';
  next();
}, (req, res) => {
  res.json({
    message: 'Hello world from Express middleware ' + res.data
  });
});

app.use('/test/', ()=>{}, ()=>{});
```

Are not the same...

**Comment by bertho-zero** [comment]
Both must be valid, we must be able to mix middleware and arrays of middleware.

**Comment by MichaelJCole** [comment]
@bertho-zero Sounds good to me :-)  I noticed the communication was inconsistent with the example.

I'm guessing this is proxied to express's use.  http://expressjs.com/en/4x/api.html#app.use

We could copy that description or link to it.  Express documents it like this:

```
app.use([path,] callback [, callback...])

path 
| The path for which the middleware function is invoked; can be any of:
A string representing a path.
A path pattern.
A regular expression pattern to match paths.
An array of combinations of any of the above.

callback 
| Callback functions; can be:
A middleware function.
A series of middleware functions (separated by commas).
An array of middleware functions.
A combination of all of the above.
```

**Comment by daffl** [comment]
This should be up to date now.
