### ISSUE TITLE
Comment: Errors (api/errors.md)

### ISSUE THREAD

**Issue by MichaelJCole** [feathersjs/docs#1275]
Hi, on this page:

https://docs.feathersjs.com/api/errors.html#error-handling

There is a section about error handling, and what looks like an older style of code to create the example.  

Below is the same code in a format similar to "log" from [feathers generate app](https://docs.feathersjs.com/guides/chat/creating.html#generating-the-application)

Is this error handling information important or out-of-date?  

And if it's important, why isn't it here:
https://docs.feathersjs.com/api/express.html#expresserrorhandler

Or in the guide (maybe as an advanced topic?):  https://docs.feathersjs.com/guides/advanced/readme.html

It just seems like it's either outdated or rather important.

```
const errors = require('@feathersjs/errors');

module.exports = function () {
  return context => {
    if (context.error) {
      const error = context.error;
      if (!error.code) {
        const newError = new errors.GeneralError('server error');
        context.error = newError;
        return context;
      }
      if (error.code === 404 || process.env.NODE_ENV === 'production') {
        error.stack = null;
      }
      return context;
    }
  };
};
```
And in app.hooks.js
```
// Application hooks that run for every service
const log = require('./hooks/log');
const errorHandler = require('./hooks/errorHandler');

module.exports = {
  ...
  error: {
    all: [ errorHandler(), log() ],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};
```

**Comment by daffl** [comment]
The example talks about general error handling (and rewriting) for Feathers where the Express transport chapter shows how to configure the error handler middleware. If you want to update the example to what you are suggesting, a pull request would be welcome.

**Comment by MichaelJCole** [comment]
Hi @daffl,  

express.errorHandler() lives on
```
const express = require('@feathersjs/express');
const app = express(feathers());
app.use(express.errorHandler())
```

Is there a reason that Feathers errorHandler() couldn't live on:
```
const { errorHandler } = require('@feathersjs/express');
module.exports = {
  //...
  error: {
    all: [errorHandler],
    find: [],
```

Using the code in the example as the reference implementation?

Would you take a PR for that?

**Comment by daffl** [comment]
What are you suggesting that error handler should do? The example really just shows how you could modify a service method error to return a different response but since most adapters already throw Feathers errors this usually isn't necessary and a generated application already includes an [error logging hook](https://github.com/feathersjs/feathers-chat/blob/master/src/app.hooks.js#L26).

**Comment by MichaelJCole** [comment]
Hey David, I'm not advocating so much as trying to understand.  

That page says: "It is important to make sure that errors get cleaned up before they go back to the client."
Then lists some code.  That code isn't in the Feather app that was generated, 

So I'm trying to resolve it either by clarifying the docs or adding the missing code in my app.

The code for the logger is different than the errorHandler.  It looks like the errorHandler does a type conversion for non-REST transports.  Is that necessary?

```
// src/hooks/log.js

// A hook that logs service method before, after and error
// See https://github.com/winstonjs/winston for documentation
// about the logger.
const logger = require('../logger');
const util = require('util');

// To see more detailed messages, uncomment the following line:
// logger.level = 'debug';

module.exports = function () {
  return context => {
    // This debugs the service call and a stringified version of the hook context
    // You can customize the message (and logger) to your needs
    logger.debug(`${context.type} app.service('${context.path}').${context.method}()`);
    
    if(typeof context.toJSON === 'function' && logger.level === 'debug') {
      logger.debug('Hook Context', util.inspect(context, {colors: false}));
    }
    
    if(context.error && !context.result) {
      logger.error(context.error.stack);
    }
  };
};

```
versus
```
//  example
const errors = require('@feathersjs/errors');

module.exports = function () {
  return context => {
    if (context.error) {
      const error = context.error;
      if (!error.code) {
        const newError = new errors.GeneralError('server error');
        context.error = newError;
        return context;
      }
      if (error.code === 404 || process.env.NODE_ENV === 'production') {
        error.stack = null;
      }
      return context;
    }
  };
};
```

**Comment by daffl** [comment]
There is not really anything you have to do if the errors you are getting on the client don't contain any information you don't want that client to see. Both examples you posted are error hooks. What you do in a hook is entirely up to you. How hooks work is documented in the [hooks guide](https://docs.feathersjs.com/guides/basics/hooks.html), the [processing data chapter](https://docs.feathersjs.com/guides/chat/processing.html) in the chat application guide and the [hooks API](https://docs.feathersjs.com/api/hooks.html). Modifying `context.error` in a hook is the same thing as modifying e.g. `context.result`.
