### ISSUE TITLE
pdf download 503 Error

### ISSUE THREAD

**Issue by fuzzthink** [feathersjs/docs#1280]
On https://raw.githubusercontent.com/feathersjs/docs/master/feathersjs.pdf , Getting:

```
Error 503 Backend is unhealthy
Backend is unhealthy

Guru Mediation:
Details: cache-bwi5150-BWI 1553190781 4155265527

Varnish cache server
```

**Comment by daffl** [comment]
Try clearing your browser cache or opening the link in incognito mode.

**Comment by fuzzthink** [comment]
Works now, no cache clearing or incognito needed.
