### ISSUE TITLE
Possible Bug with  REST (api/client/rest.md)

### ISSUE THREAD

**Issue by frastlin** [feathersjs/docs#1288]
### Comment/Problem

Hello, I have a google apps script that I am trying to connect to a feathers server, so I need to do all the requests by hand rather than using the feathers client.

When I send a blank get request to view all the items in the service that is behind authentication, I get: 

> {"name":"GeneralError","message":"An id must be provided to the 'get' method","code":500,"className":"general-error","data":{},"errors":{}}

This is with my jwt in the header. Is there another way of getting all the items in a service? Or getting all items where the _id exists.

I'm using the feathers chat example. When I send the exact same method to the users service, I get a listing of all the users.

### System configuration (optional)

I'm using Firefox and node 10.15.1. I'm using the example chat application. I'm on Windows and using npm.

**Comment by daffl** [comment]
In the Feathers client, the method to get all items is [service.find()](https://docs.feathersjs.com/api/services.html#findparams). [service.get(id)](https://docs.feathersjs.com/api/services.html#getid-params) is only used for specific items.

**Comment by frastlin** [comment]
I need the curl command. I'm only using curl.

**Comment by daffl** [comment]
As documented in the [HTTP client API](https://docs.feathersjs.com/api/client/rest.html#http-api) a `GET /messages` should give you all messages.

**Comment by frastlin** [comment]
Here is my curl request:

    curl -X get -H 'Content-Type: application/json' -H 'Authorization: my_token -i http://localhost:3030/messages

If I change that exact call to users:

    curl -X get -H 'Content-Type: application/json' -H 'Authorization: my_token -i http://localhost:3030/users

Then I get a list of users, but users does not require authentication.

**Comment by frastlin** [comment]
I found the problem. Apparently there was one entry that was not formatted correctly, it was missing a userId. I commented out loading all the hooks on the messages hook, then was able to run the above request just fine.
The error message didn't point me to the populate-user after hook at all.
Thanks,
