### ISSUE TITLE
How can I deploy featherjs api to Plesk? 

### ISSUE THREAD

**Issue by tong9977** [feathersjs/docs#1293]
How can I deploy featherjs api to Plesk? 
I use featherjs to develop REST API. It works very well.
Now I want to deploy  REST API to my web hosting. There are node 10.0.1 installed on Plesk (Window Server) already.
I search on google but I have no luck.
Do you have any example?

THANK YOU

**Comment by daffl** [comment]
Feathers works like any other Express or Socket.io NodeJS server. You may get a better answer on how to deploy those with your hosting provider.
