### ISSUE TITLE
Please explain closing of server and connections: Writing tests (guides/chat/testing.md)

### ISSUE THREAD

**Issue by emahuni** [feathersjs/docs#1294]
### Comment/Problem

I was having this problem with my tests:
```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```
Then I had to search and hit this issue page to solve it:
[Gracefully shutting down feathers for testing purposes](https://github.com/feathersjs/feathers/issues/377)
The AVA suggestion is stupid I think cause it means AVA is not able to detect issues that Jest is detecting. The question is does AVA close the open connections etc or it thinks everything is super?

What I got from the issue is the following and it works:

```
afterAll(function(function(done) {
  app.get('mongooseClient').disconnect()
  app.socket.disconnect();
  app.server.close(done);
});
```

Why isn't this in the documentation was my concern. At least give an example and explain this.

### System configuration (optional)

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

Testing Suite: Jest

**NodeJS version**: 11

**Operating System**: OSx

**Browser Version**: Chrome 74

**React Native Version**: N/A I use VueJS

**Module Loader**: Webpack

**Comment by daffl** [comment]
This message should be solved in the docs of Feathers v4
