### ISSUE TITLE
Comment: Express (api/express.md)

### ISSUE THREAD

**Issue by khalibloo** [feathersjs/docs#1296]
### Comment/Problem

Is there a way to automatically generate API docs (a browsable API interface) like Django Rest Framework does? I've seen mentions of Swagger and other tools, but those seem to rely heavily on manual input rather than automatic generation of the docs if I understand correctly.

I'm evaluating feathers for a team project, and having a reliable presentable always-up-to-date apidoc would be essential for the UI devs.

**Comment by daffl** [comment]
[feathers-swagger](https://github.com/feathersjs-ecosystem/feathers-swagger) does generate documentation for the service endpoints automatically. You'll just have to add the descriptions and documentation for other custom behaviour.
