### ISSUE TITLE
Comment: Hooks (api/hooks.md) What About Editing the data in an After Hook?

### ISSUE THREAD

**Issue by frastlin** [feathersjs/docs#1297]
### Comment

I have some data that needs to sink with another API on a create and patch method. I would like to add the ID of the other API's newly created entry to the new entry on my database.
I don't know how fast the other API will be, and I would like to have the created data in my DB ASAP.
What is the safest way to do this?
My theory is that using an after hook would be the best option. But what is the safest way of updating the entry in my DB with the ID from the other DB? Should I use context.service.patch with the context.data._id? Or is there a better way?

**Comment by daffl** [comment]
Yep, you can `context.service.patch` with the `_id`. If you don't `await` or return that promise in the hook the request also won't wait until it returns if that is something you'd like to do.
