### ISSUE TITLE
Comment: Generating a service (guides/chat/service.md)

### ISSUE THREAD

**Issue by Tavethiya** [feathersjs/docs#1298]
>feathers generate service
× It does not look like this application has been generated with this version of the generator or the required `directories.lib` has been removed from package.json.

**Comment by daffl** [comment]
Basically what the error message says. Check that `{ "directories": { "lib" } }` is set in your `package.json` (example [here](https://github.com/feathersjs/feathers-chat/blob/master/package.json#L17)). You probably want to run `feathers upgrade` to upgrade to the latest version.
