### ISSUE TITLE
Comment: Querying (api/databases/querying.md)

### ISSUE THREAD

**Issue by TheDarkPleco** [feathersjs/docs#1300]
### Comment/Problem

Hello,
I had been looking through the documentation of the FeathersJS website and noticed there was no documentation on the $and option for querying. It had taken me quite a while to figure out that someone had actually made the fix in the repository and that I did not need to create a workaround for the lack of an option. I am just writing this to make sure folks know that the (awesome to have) option is not yet documented for the public. Thank you for your time.

**Comment by daffl** [comment]
It is only available for certain database adapters, not everywhere. By default query parameters are automatically `and`ed.
