### ISSUE TITLE
Comment: Client (api/authentication/client.md)

### ISSUE THREAD

**Issue by faustAbc** [feathersjs/docs#1302]
### Problem

`client.get('auth')` returns undefined.

Client code is below: 

```javascript
import io from 'socket.io-client';
import feathers from '@feathersjs/feathers';
import socketio from '@feathersjs/socketio-client';
import auth from '@feathersjs/authentication-client';

const socket = io(feathersConfig.path);
const client = feathers();

client
  .configure(socketio(socket))
  .configure(auth({ my-super-config }));

client.get('auth');
```

**Comment by daffl** [comment]
There is no `auth` property on the client. You have to call `app.authenticate()` as shown in the [frontend guide](https://docs.feathersjs.com/guides/chat/frontend.html) and the [authentication client API](https://docs.feathersjs.com/api/authentication/client.html).

**Comment by faustAbc** [comment]
Thank you!
