### ISSUE TITLE
Comment: Usage (api/client.md)

### ISSUE THREAD

**Issue by abbasasad057** [feathersjs/docs#1308]
### Comment/Problem
When I run script as described in docs as shown below 
define(function (require) {
  const feathers = require('@feathersjs/client');
  const io = require('socket.io-client');

  const socket = io('http://localhost:3030');
  // @feathersjs/client is exposed as the `feathers` global.
  const app = feathers();

  app.configure(feathers.socketio(socket));
  app.configure(feathers.authentication());

  app.service('messages').create({
    text: 'A new message'
  });
});
I get index.js:1 Uncaught ReferenceError: define is not defined
How I can I solve this issue

**Comment by daffl** [comment]
This code only applies when using [RequireJS](https://requirejs.org/) as the module loader.
