### ISSUE TITLE
Comment: Adding authentication (guides/chat/authentication.md)

### ISSUE THREAD

**Issue by SephReed** [feathersjs/docs#1313]
### Comment/Problem

Using a cli to generate an app is cool, but very hard to trust when integrating with an existing app.  There's a lot of unknowns in how it will effect my project, and it's simply not an option.

Further, the docs focus a lot on a "learn as you go" approach, but I really don't want to be shown the wrong way to do something first.

If you could please include a complete, copy paste-able, single file project somewhere upfront, that would make life a lot easier for us users.  And by complete, I mean making some use of every need to know function.

**Comment by daffl** [comment]
There are tons of resource to do this from the [feathers-chat]Ohttps://github.com/feathersjs/feathers-chat) repository to a [long list of examples](https://github.com/feathersjs/awesome-feathersjs#examples) in the [awesome-feathersjs](https://github.com/feathersjs/awesome-feathersjs) repository.

The guide is also currently being overhauled to be more concise and to the point.

**Comment by SephReed** [comment]
Don't make it hard, a single page app showing a basic usage of the "need to know" features is all it takes to get a user primed.  Then, if you have type definitions and they're using typescript, users can just poke at the example, slowly answering their own questions.

The trick is to give users a way to simultaneously ask and find out.  Doing an up front data dump is, sadly, not very effective in user testing.

Once I'm done with getting this up and running, I'll write a medium post and link it here.

It's a lovely project you have, I quite like the code style.

**Comment by SephReed** [comment]
Oh.  Very important.  Single page app must be copy paste-able, and then runs immediately.  Do some user testing, and make sure the average user has a feathers project up and running within 5-10 min of getting the starting page, without using any new tools (ie a cli).  Just npm and their code editor.

**Comment by daffl** [comment]
A complete copy and paste example is directly on the homepage at https://feathersjs.com. Seems like people don't scroll down there though so part of the plan is to move it into the guide.

**Comment by SephReed** [comment]
I did see that one, and it was a good start for sure.  The type of example I'm speaking of is more around the 90-120 line size.  Big enough to really fit every major feature (and maybe some comments), but small enough to not be too overwhelming.

Like, right at the point where a project starts to get momentum.
