### ISSUE TITLE
Font used in new docs

### ISSUE THREAD

**Issue by anonimusprogramus** [feathersjs/docs#1320]
### Suggestion

I find it a lilte bit harder on eyes reading new docs ([crow](https://crow.docs.feathersjs.com)) .

For comparison, I read [this guide](https://vue-composition-api-rfc.netlify.com), it's easy on the eyes, **both** desktop or mobile. Please have a look.

Would it be OK to have another font type?

Thanks

**Comment by daffl** [comment]
Fair point. I actually just realized that Raleway is mainly meant for headings and larger typesetting. Just checking with the designer what would be a good complementary font and then adding it to #1324
