### ISSUE TITLE
IIFE

### ISSUE THREAD

**Issue by anonimusprogramus** [feathersjs/docs#1321]
### Suggestion

The [new docs](https://crow.docs.feathersjs.com/guides/basics/starting.html#what-s-next) uses [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE). This may cause error for users who prefer to write code without **semicolon** (or set Prettier's config `"semi" : false`)

It's better to put a little helpful info about this, avoiding such potential problem.

Thanks @daffl 

`The error`
![Screenshot_20190822_234053](https://user-images.githubusercontent.com/7464749/63533233-8ca46280-c536-11e9-9cfe-dacb8a3de322.png)

`Small hack`
![Screenshot_20190822_234151](https://user-images.githubusercontent.com/7464749/63533234-8ca46280-c536-11e9-822b-cb920e897db4.png)

**Comment by daffl** [comment]
Makes sense. I change it to use and call a `main` function instead in #1324. That way this shouldn't be an issue either way.
