### ISSUE TITLE
Comment: Services (api/services.md)

### ISSUE THREAD

**Issue by SephReed** [feathersjs/docs#1323]
How do I make a service with hooks, but no endpoint? 

Why is the thing returned by app.service() different than the thing put into app.use()?

**Comment by daffl** [comment]
This is [explained in the API docs](https://docs.feathersjs.com/api/services.html#feathers-functionality). A standalone service at the moment can also be created like this:

```js
function standaloneService(service, hooks) {
  return feathers().use('/', service).service('/').hooks(hooks);
}
```
