### ISSUE TITLE
Comment: Authentication (guides/basics/authentication.md)

### ISSUE THREAD

**Issue by awimberly** [feathersjs/docs#1338]
Can you show the full default.json file. I am getting parsiong errors when I use npm run dev

**Comment by daffl** [comment]
It would help if you could share the one that's getting parsing errors. Also remember everything is available as a reference in the [feathers-chat](https://github.com/feathersjs/feathers-chat) repository.

**Comment by awimberly** [comment]
Hey @daffl! Sorry about that. I did check the full repository. I was still getting some errors. I will post later. I am sure the mistake is on my part. Thanks for the quick response!
