### ISSUE TITLE
Comment: Authentication (guides/basics/authentication.md)

### ISSUE THREAD

**Issue by Ryan-Priestly** [feathersjs/docs#1339]
Tell us about your issue or comment. Please be as specific as possible.

https://docs.feathersjs.com/guides/basics/authentication.html#typescript code section is blank, there is simply nothing in there...

**Comment by daffl** [comment]
Oops, indeed. Added in https://github.com/feathersjs/docs/pull/1349 and to the chat in https://github.com/feathersjs/feathers-chat-ts/commit/68199867db77d7b477f3ebde3184efd7394307fa
