### ISSUE TITLE
Comment: Authentication (guides/basics/authentication.md)

### ISSUE THREAD

**Issue by osamaxsyed** [feathersjs/docs#1340]
**In section Registering a User when I try the following:**

curl 'http://localhost:3030/users/' \
  -H 'Content-Type: application/json' \
  --data-binary '{ "email": "hello@feathersjs.com", "password": "supersecret" }'

**I get the following response:**

Access Denied (authentication_failed)
--
Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified.
This is typically caused by an incorrect username and/or password, but could also be caused by network problems.

**Comment by daffl** [comment]
I am not able to verify this problem. The error message looks like it is from a proxy or something else but it does not come from Feathers.
