### ISSUE TITLE
Comment: Local (api/authentication/local.md)

### ISSUE THREAD

**Issue by OnePunchMan007** [feathersjs/docs#1352]
### Comment/Problem

In the documentation 
Configuration

The following settings are available:

    usernameField: Name of the username field in the (e.g. 'email')

Missing something at the end of : "Name of the username field in the" Database ?

**Comment by bartduisters** [comment]
If there is something that can be more clear or is just plain wrong, you can edit that line and open a pull request. If it indeed is something that is unclear or is improved by the change, it will get merged by the maintainers.

Here a step-by-step guide on how to do this:

1. On the page with the mistake, scroll down and click 'edit this page'
![image](https://user-images.githubusercontent.com/43420049/64894196-61b2b780-d679-11e9-95e1-ad282afcfb2f.png)

2. Find the mistake on the page
![image](https://user-images.githubusercontent.com/43420049/64894224-742cf100-d679-11e9-814e-606838e9f4f0.png)

3. Apply the change you think is necessary
![image](https://user-images.githubusercontent.com/43420049/64894246-7e4eef80-d679-11e9-81de-813e2b03eaf9.png)

4. Fill in the information and click on 'Propose a file change'
![image](https://user-images.githubusercontent.com/43420049/64894293-97f03700-d679-11e9-8a16-5ea013985f5c.png)

5. If it is 'able to merge', click on 'Create pull request'
![image](https://user-images.githubusercontent.com/43420049/64894312-a3436280-d679-11e9-9a3e-511c6b053467.png)

6. Click on 'Create pull request' again
![image](https://user-images.githubusercontent.com/43420049/64894326-aa6a7080-d679-11e9-8fc1-baf59175cd4f.png)

7. When all checks are 'green' and a maintainer sees the awesome change you did, it will either get merged or declined
![image](https://user-images.githubusercontent.com/43420049/64894355-c0783100-d679-11e9-8dc0-68eae7c50bd4.png)

**Comment by daffl** [comment]
Tanks @bartduisters, this is great. I added your instructions as a saved reply so we can use i in the future. Closed via #1355
