### ISSUE TITLE
Comment: Authentication (guides/basics/authentication.md)

### ISSUE THREAD

**Issue by 2JN** [feathersjs/docs#1361]
### Comment/Problem

How do you specify a timeout for a request on the authentication hook?
Right now the timeout if an invalid user is trying to access is 3 seconds but I would like it to me it shorter.

**Module versions** (especially the part that's not working):
"@feathersjs/feathers": "^3.1.7",
"@feathersjs/authentication": "^2.1.7",
"@feathersjs/authentication-jwt": "^2.0.1",
"@feathersjs/authentication-local": "^1.2.1",
**NodeJS version**:
10.15.0
**Operating System**:
Pop OS
**Browser Version**:
Firefox 69
**React Native Version**:

**Comment by daffl** [comment]
You are using an old version of Feathers. For the guide to work, all `@feathersjs/` modules should show version 4.3.0 or later.
