### ISSUE TITLE
[Suggestion] Dark Mode ready implementation

### ISSUE THREAD

**Issue by matiaslopezd** [feathersjs/docs#1378]
I propose add dark mode to the documentation with this code, copy&paste!

See here more:

https://gist.github.com/matiaslopezd/86a7450c92620cb9f4d179677cd279e2

**Comment by matiaslopezd** [comment]
![image](https://user-images.githubusercontent.com/23618492/66499856-fb159380-ea96-11e9-8cd0-167f0abbfabe.png)

**Comment by matiaslopezd** [comment]
![image](https://user-images.githubusercontent.com/23618492/66499933-1a142580-ea97-11e9-9f87-a4ade477c847.png)

**Comment by matiaslopezd** [comment]
![image](https://user-images.githubusercontent.com/23618492/66500308-ac1c2e00-ea97-11e9-907c-20a54f495de5.png)
![image](https://user-images.githubusercontent.com/23618492/66500169-76774500-ea97-11e9-88d3-f9972903910e.png)
![image](https://user-images.githubusercontent.com/23618492/66500198-84c56100-ea97-11e9-8c3b-d4a6e9946499.png)
![image](https://user-images.githubusercontent.com/23618492/66500260-97d83100-ea97-11e9-8441-6f4dfa5ff951.png)
![image](https://user-images.githubusercontent.com/23618492/66500358-be966780-ea97-11e9-99f9-d47a858be249.png)

**Comment by matiaslopezd** [comment]
![image](https://user-images.githubusercontent.com/23618492/66507589-db399c00-eaa5-11e9-839f-82136d28f9a7.png)
![image](https://user-images.githubusercontent.com/23618492/66507613-e68cc780-eaa5-11e9-8e3c-7de1d07423d1.png)
![image](https://user-images.githubusercontent.com/23618492/66507646-f2788980-eaa5-11e9-910f-437873a8cd38.png)
![image](https://user-images.githubusercontent.com/23618492/66507654-f9070100-eaa5-11e9-92db-c2b971a93deb.png)
![image](https://user-images.githubusercontent.com/23618492/66507680-06bc8680-eaa6-11e9-9bcf-8ae2e134ef4e.png)
![image](https://user-images.githubusercontent.com/23618492/66507705-12a84880-eaa6-11e9-9c97-724fd66f551b.png)

**Comment by daffl** [comment]
Thank you for the suggestion. The documentation is built on [Vuepress](https://vuepress.vuejs.org/). A pull request adding a switcher would be very welcome. I also believe @DesignByOnyx created a dark mode theme using a browser plugin for the previous documentation before, maybe this could be integrated there as well.

**Comment by DesignByOnyx** [comment]
Indeed I have, and it's updated for the v4 release. If you're an "everything must be dark" person like myself, then you probably already have an USO loader in your browser (I use [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en) as it's easy and they are committed to not selling to some cheap ad agency).

You are also welcome to create your own styles on https://userstyles.org - anyone with a USO plugin will then see your custom themes.

**Comment by daffl** [comment]
This is now available at https://docs.feathersjs.com/ thanks to @mhillerstrom.
