### ISSUE TITLE
I wish you could change the way we select an option to USING NUMBERS instead of using arrow keys in the feathers/CLI prompts when generating a project, service, hook, etc.  It would be easier, more accurate and time-saving; and less frustrating (struggling to pick the desired choice, and having to repeat the same process over and over).

### ISSUE THREAD

**Issue by krispi1** [feathersjs/docs#1380]
### Comment/Problem

Tell us about your issue or comment. Please be as specific as possible.

If you would like to point out a typo, wording or code issue, please submit a pull request with a suggested fix instead by following the "Edit this page" link.

### System configuration (optional)

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
This might be addressed via https://github.com/feathersjs/cli/issues/253
