### ISSUE TITLE
Where put those peaces of code?

### ISSUE THREAD

**Issue by Tunizoo** [feathersjs/docs#1383]
It is not shown where to put the peaces of code mentioned in this page.

**Comment by daffl** [comment]
You did not link any code.

**Comment by Tunizoo** [comment]
I mean: the code in pages "registering services" and "service events" of
the tutorial.

‫في الجمعة، 11 أكتوبر 2019 في 4:18 م تمت كتابة ما يلي بواسطة ‪David
Luecke‬‏ <‪notifications@github.com‬‏>:‬
