### ISSUE TITLE
examples for using methods

### ISSUE THREAD

**Issue by Tunizoo** [feathersjs/docs#1384]
I would like to see examples of using service methods (create, update...)

**Comment by daffl** [comment]
There are many examples in [the guide](https://docs.feathersjs.com/guides/) starting with the [Quick start](https://docs.feathersjs.com/guides/basics/starting.html), [Hooks](https://docs.feathersjs.com/guides/basics/hooks.html) and [Writing tests](https://docs.feathersjs.com/guides/basics/testing.html), the [feathers-chat application](https://github.com/feathersjs/feathers-chat) as well as the [service API documentation](https://docs.feathersjs.com/api/services.html#service-methods).

**Comment by Tunizoo** [comment]
sorry, I mean how to personnalize a service (other than users) and use
methods of the service class (get, find, create...) In fact, it is not so
simple: when I try to change small things I get fatal errors.. Clear
examples should be much benefic...

‫في الأحد، 13 أكتوبر 2019 في 5:31 م تمت كتابة ما يلي بواسطة ‪David Luecke‬‏
<‪notifications@github.com‬‏>:‬

**Comment by daffl** [comment]
If you have any specific problems, please share a repository or code that shows the problem.

**Comment by Tunizoo** [comment]
I use feathers in back end. I access it through localhost:3030. I would
like to know how to access data for my service 'devices'
(device_class,device_parent): how to use get and create functions in this
case

‫في الأربعاء، 16 أكتوبر 2019 في 5:37 م تمت كتابة ما يلي بواسطة ‪David
Luecke‬‏ <‪notifications@github.com‬‏>:‬

**Comment by daffl** [comment]
Did you follow [the guide](https://docs.feathersjs.com/guides/)? It shows exactly that. If you are not using Feathers on the client, the direct communication is also documented [here for REST](https://docs.feathersjs.com/api/client/rest.html#http-api) and [here for Socket.io](https://docs.feathersjs.com/api/client/socketio.html#direct-connection)

**Comment by Tunizoo** [comment]
THANKS!

‫في الخميس، 17 أكتوبر 2019 في 4:30 م تمت كتابة ما يلي بواسطة ‪David
Luecke‬‏ <‪notifications@github.com‬‏>:‬
