### ISSUE TITLE
V4 Get the latest version documentation in pdf format 

### ISSUE THREAD

**Issue by skaptox** [feathersjs/docs#1385]
### Comment/Problem

Hello, is there a way to get the documentation of the latest version in pdf format?

In the previous version you can downloaded it.

![image](https://user-images.githubusercontent.com/29805241/66717240-b0509000-eda4-11e9-88f7-97c1800514fe.png)

**Comment by daffl** [comment]
This is due to the migration to [Vuepress](https://vuepress.vuejs.org/) away from GitBook (which is no longer maintained as open source). There is a Vuepress plugin at https://github.com/ulivz/vuepress-plugin-export. I briefly tried it and it does export a PDF but it isn't  in a great format.
