### ISSUE TITLE
Command succeds in fethersjs server, but not the client equivalent

### ISSUE THREAD

**Issue by Tunizoo** [feathersjs/docs#1390]
God has helped me to bypass the precedent problem, but I 've faced another:
the command app.service('messages').create({ text: 'I really have to iron' }, {}) succeeds,
but its equivalent from client does not (socket.emit('create', 'messages', {
  text: 'I really have to iron'
}, (error, message) => {
  console.log('Todo created', message);
});)
 it does not generate an error message, but nothing happens in the database. The same for the command find(): it does not get the new message created in the database..

**Comment by Tunizoo** [comment]
THIS IS MY FULL CODE:
const socket = io('http://localhost:3030');
const client = feathers();

client.configure(feathers.socketio(socket));

client.configure(feathers.authentication({
  storage: window.localStorage
}));

const authenticate = async () => {
  try {
    console.log("user reauthentication");
    return await client.reAuthenticate();
  } catch (error) {
    window.location.href="login.html";
    return await client.authenticate({
      strategy: 'local',
      email: document.getElementById('email').value,
      password: document.getElementById('password').value
    });
  }
};
async function getToken(){
  token= (await authenticate()).accessToken;
  console.log(token);
}
socket.on('connect', () => {
  socket.emit('create', 'authentication', {
    strategy: 'jwt',
    accessToken: getToken()
  }, function(error, newAuthResult) {
    console.log(newAuthResult); 
  });
});

socket.emit('find', 'devices', { status: 'read', user: 10 }, (error, data) => {
  console.log('Found all messages', data);
});
socket.emit('create', 'devices', {
  text:"example"
}, (error, message) => {
  console.log('Todo created', message);
});

**Comment by daffl** [comment]
Please post your operating system and `@feathersjs` module versions. Also if you are using Feathers on the client you don't need to send any events on the socket yourself.

**Comment by Tunizoo** [comment]
Ubuntu 19.04
feathers version: 6.11.3




‫في الأحد، 20 أكتوبر 2019 في 7:21 م تمت كتابة ما يلي بواسطة ‪David Luecke‬‏
<‪notifications@github.com‬‏>:‬

**Comment by Tunizoo** [comment]
ubuntu 19.04
feathersjs 6.11.3

**Comment by daffl** [comment]
That is not a Feathers version. I was asking about the versions of the `@feathersjs` dependencies in your `package.json`. I also really recommend to [follow the guide](https://docs.feathersjs.com/guides/) to get a better idea how everything fits together.

**Comment by Tunizoo** [comment]
Sorry, i've simply wrote "feathersjs --version" and that was the response.
But the dependencies were:
  "dependencies": {
    "@feathersjs/authentication": "^4.3.5",
    "@feathersjs/authentication-local": "^4.3.5",
    "@feathersjs/authentication-oauth": "^4.3.5",
    "@feathersjs/configuration": "^4.3.4",
    "@feathersjs/errors": "^4.3.4",
    "@feathersjs/express": "^4.3.5",
    "@feathersjs/feathers": "^4.3.4",
    "@feathersjs/socketio": "^4.3.5",
    "@feathersjs/socketio-client": "^4.3.7",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "feathers-sequelize": "^6.0.2",
    "helmet": "^3.21.1",
    "mysql2": "^1.7.0",
    "sequelize": "^5.19.4",
    "serve-favicon": "^2.5.0",
    "winston": "^3.2.1"
  },

‫في الثلاثاء، 22 أكتوبر 2019 في 4:08 م تمت كتابة ما يلي بواسطة ‪David
Luecke‬‏ <‪notifications@github.com‬‏>:‬

**Comment by Tunizoo** [comment]
Thanks to God! and thanks to you, after that. The problem was simply that
the commands create or find need to force them to be executed after
authentication; this has been resolved with async and await.

‫في الثلاثاء، 22 أكتوبر 2019 في 6:17 م تمت كتابة ما يلي بواسطة ‪nyzar
Sfax‬‏ <‪nyzarmhiri@gmail.com‬‏>:‬
