### ISSUE TITLE
Comment: Hooks (api/hooks.md)

### ISSUE THREAD

**Issue by gibraltar** [feathersjs/docs#1391]
### Comment/Problem

Tell us about your issue or comment. Please be as specific as possible.

If you would like to point out a typo, wording or code issue, please submit a pull request with a suggested fix instead by following the "Edit this page" link.

### System configuration (optional)

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:
12

**Operating System**:
MacOS

**Browser Version**:
Chrome latest

**React Native Version**:

**Module Loader**:

I am having an issue no hooks are being executed when running mocha tests. Actual application during development works fine, its just mock tests do not execute any hooks, even when creating user password is not getting hashed.

**Comment by daffl** [comment]
Some built in hooks (like `authenticate`) do not run for internal calls ([params.provider](https://docs.feathersjs.com/api/services.html#params) is not set) but it is hard to tell what is happening without the test in question to reproduce.

**Comment by gibraltar** [comment]
Issue was I was trying to use the Memory adapter .. where I need to add in the hooks manually through configure in Mocha tests .. so issue kind of solved :)
