### ISSUE TITLE
Comment: Authentication (guides/basics/authentication.md)

### ISSUE THREAD

**Issue by UlyssesAlves** [feathersjs/docs#1394]
### Comment/Problem

Got an error while trying to register a new user by following feathers tutorial.

{
    "name": "GeneralError",
    "message": "Service method 'create' for 'users' service must return a promise",
    "code": 500,
    "className": "general-error",
    "data": {},
    "errors": {}
}

### System configuration (optional)

FeathersJS application created following FeathersJS docs tutorial.

**Module versions** (especially the part that's not working):
users

**NodeJS version**: 10.16.3

**Operating System**: Windows 10

**Comment by UlyssesAlves** [comment]
I've just fixed it in my copy of the code example.

As it is documented, [the tutorial](https://docs.feathersjs.com/guides/basics/services.html#customizing-a-service) is missing the async keyword on the create method and also lacks the await in the return statement inside this method.

Here is the original code, which appears to have the bug:

```
exports.Users = class Users extends Service {
  create (data, params) {
   // ...
    return super.create(userData, params);
  }  
};
```

And here is my fixed version:

```
exports.Users = class Users extends Service {
  async create(data, params) {
  	// ...
    return await super.create(userData, params);
  }
};
```

**Comment by daffl** [comment]
I'm not sure if that was the issue since `super.create(userData, params);` already returns a promise (so the additional `await` also wouldn't be necessary). It's working as expected with the latest versions in the feathers-chat (https://github.com/feathersjs/feathers-chat/blob/master/src/services/users/users.class.js).
