### ISSUE TITLE
Clarify why app.reAuthenticate() shouldn’t be called more than once

### ISSUE THREAD

**Issue by amxmln** [feathersjs/docs#1397]
The docs for `authentication-client` warn about using `app.reAuthenticate()` more than once, however don’t explain why. I think it would be beneficial for the documentation to explain the reasoning since calling the function multiple times seems to be the simplest solution for dealing with certain issues.

For example, the user object returned by `app.get('authentication')` is outdated if the user was updated since the last (re)authentication, however since we know that it updated through events, it’s trivial to call `app.reAuthenticate(true)` and fix the issue.

**Comment by daffl** [comment]
This note was added specifically because people were calling `authenticate()` before _every_ Feathers client call that was being made. As long as it is still clear that that isn't necessary, a PR to improve that information will be welcome.
