### ISSUE TITLE
Comment: Anonymous authentication (cookbook/authentication/anonymous.md)

### ISSUE THREAD

**Issue by klausbert** [feathersjs/docs#1398]
### Comment/Problem

I'm getting a General Error 500: "app.defaultAuthentication is not a function" when pasting these functions. Any clues?

### System configuration (optional)

I have updated src/authentication.js as described in your example, src/hooks/allow-authentication.js with the example hook, and got one service where AllowAuthentication is require()d and its function inserted in the service hook as describedin the example.
The error would be happening on the authenticate() function from require('@feathersjs/authentication').hooks:

> all: [ allowAnonymous(), authenticate('jwt', 'anonymous') ],

because if I remove the authenticate('jwt', 'anonymous') it goes away (without authenticating of course)
The missing function is used in line 26:

>     const authService = app.defaultAuthentication(settings.service);

_FWIW If I inspect context.app in the allowAnonymous hook running previous to autenticate(), I can't find context.app.defaultAuthentication() so maybe something is missing from the allow-anonymous custom hook?_

**Module versions** (especially the part that's not working):

"@feathersjs/authentication": "^4.3.11"

**NodeJS version**:

11.1.0

**Operating System**:

Ubuntu 16.04

_Thanks!_

**Comment by daffl** [comment]
`app.defaultAuthentication` will be available after instantiating the authentication service. Following the guide based on the [feathers-chat](https://github.com/feathersjs/feathers-chat) works as expected so we'd need a complete repository to reproduce your issue.
