### ISSUE TITLE
Problem: Generating an app (guides/basics/generator.md)

### ISSUE THREAD

**Issue by asajuenitan** [feathersjs/docs#1413]
### Problem
Packages not fully installed after scaffolding app
**Replicate**

![Screenshot from 2020-01-01 15-47-14](https://user-images.githubusercontent.com/16443589/71642621-6a71dc80-2cae-11ea-896f-07ba3cf02d81.png)

Unavailable Packages after yarn installs packages
`feathers-nedb`
`nedb`
`@feathersjs/authentication-local`
`@feathersjs/authentication`
`@feathersjs/authentication-oauth`

**NodeJS version**: v13.3.0

**Operating System**: Elementary OS 5.1 Hera (Linux)

**Comment by daffl** [comment]
This is probably a temporary error.

```
rm -rf node_modules package-lock.json
npm install
```

Should fix it.
