### ISSUE TITLE
Comment: Hooks (api/hooks.md)

### ISSUE THREAD

**Issue by mlippert** [feathersjs/docs#1425]
### Comment/Problem
The hooks documentation says a hook _returns the context object, undefined or throws an error_ in a couple of places, but nowhere does it explain the difference between returning a `context object` and returning `undefined`.

Throwing an error is pretty clear although specifying where the handling of the error will take place might be nice.

I've got guesses as to what the difference between returning a `context object` and `undefined` might be, but I'd really feel better if the documentation gave a definitive answer.

**Comment by daffl** [comment]
If you are returning the same context object there is no difference at all. Technically you could replace the context by returning a new one but that functionality will be removed in the upcoming version where the return value will have no effect at all and the documentation will be updated accordingly.

**Comment by mlippert** [comment]
Thanks. That was my guess, and it's good to know that the option to return a new context object is going away (I have no desire to do that, but now I know not to even _think_ about it! :smiling_imp: )
And it means I can consider returning undefined (ie just returning) the better way to write new hooks.
