### ISSUE TITLE
Comment: Express (api/express.md)

### ISSUE THREAD

**Issue by sprasad19** [feathersjs/docs#1427]
How To define custom route like  
  app.use('/api/v1/users', createService(options));

  // Get our initialized service so that we can register hooks
  const service = app.service('api/v1/users');

it showing  D:\muproject\feathers\feathers1\node_modules\@feathersjs\authentication\lib\service.js:128
                throw new Error(`The '${service}' entity service does not exist (set to 'null' if it is not required)`);

**Comment by daffl** [comment]
You have to change all references to the service path. In you case the `service` option in [the authentication configuration](https://docs.feathersjs.com/api/authentication/service.html#configuration).
