### ISSUE TITLE
Comment: Authentication (guides/basics/authentication.md)

### ISSUE THREAD

**Issue by gitwu-denver** [feathersjs/docs#1430]
### Comment/Problem

this page wasn't clear in terms of the contents of app.js.  i copied the suggested code into a new public/app.js file but it would not run.  can't tell if you're supposed to use the same contents as the quick start app.js file that is linked?  but that also did not work.  everything else has been step by step but this part seemed to skip or assume certain configuration?

**Comment by daffl** [comment]
What does "not run" mean? It'll just print the authentication information if you open the console _first_ and then visit [localhost:3030](http://localhost:3030/).
