### ISSUE TITLE
Comment: Events (api/events.md) Where is the Blanket CRUD Event

### ISSUE THREAD

**Issue by frastlin** [feathersjs/docs#1434]
### Comment/Problem

I have a data table that should stay in-sync with the server, and the user can update, create, or remove items. Is there a universal event that runs for all CRUD events?

**Comment by daffl** [comment]
There is no general event for this. Since the events you'll get are known it's pretty easy to implement yourself:

```js
['created', 'updated', 'patched', 'removed'].forEach(event => {
  service.on(event, data => service.emit('crudEvent', data));
})
```

[app.mixins](https://docs.feathersjs.com/api/application.html#mixins) might be helpful here as well.
