### ISSUE TITLE
Comment: Writing tests (guides/basics/testing.md) - Minor typos for Windows users

### ISSUE THREAD

**Issue by PierreBader** [feathersjs/docs#1452]
### Comment/Problem

I have spotted two minor typos in the article that lead to some frustration for us, Windows users, contrasting with the stunning quality of the documentation.

https://docs.feathersjs.com/guides/basics/testing.html#test-database-setup :

```
On Windows the mocha command should look like this:
npm run clean & SET NODE_ENV=test & mocha test/ --recursive --exit
```
==> remove the space between test and &

I just discovered Feathers, and it looks like we are going to spend some wonderful time together ;-)
Pierre

**Comment by daffl** [comment]
A pull request via the ["Edit this page"](https://github.com/feathersjs/docs/edit/master/guides/basics/testing.md) link with a correction would be very welcome 😄

**Comment by PierreBader** [comment]
> A pull request via the ["Edit this page"](https://github.com/feathersjs/docs/edit/master/guides/basics/testing.md) link with a correction would be very welcome 😄
Noob here.
I spend countless hours lurking in the shadows of GitHub, after many years I still have got to learn the dos and the don'ts.
Thanks for your patience !
