### ISSUE TITLE
Comment: Hooks (guides/basics/hooks.md)

### ISSUE THREAD

**Issue by mdartic** [feathersjs/docs#1462]
### Comment/Problem

In the [hooks vs extending services](https://docs.feathersjs.com/guides/basics/hooks.html#hooks-vs-extending-services), you talk about **database service** in this paragraph : 

> Extend a database service when
>
>    The functionality is only needed in this one place
>    The service could not function without it

Maybe it's for every service, so it could be "Extend a **service** when" ? (without database) ?

**Comment by daffl** [comment]
That sounds good, a pull request would be great.
