### ISSUE TITLE
React native io ping interval and timeout looks obsolete

### ISSUE THREAD

**Issue by soullivaneuh** [feathersjs/docs#1466]
### Comment/Problem

Ref: https://docs.feathersjs.com/api/client.html#react-native

On the first code block, you suggest to configure the client calling `socketio` with the socket object as argument:

```typescript
client.configure(socketio(socket));
```

This works. On the second block, you suggest to adjust the `pingInterval` and `pingTimeout` option to prevent android issues:

```typescript
const app = feathers();
const socketio = require('feathers-socketio');

app.configure(socketio({
  pingInterval: 10000,
  pingTimeout: 50000
}));
```

But:

- The require package is not the same and does not looks to exist anymore (`feathers-socketio`)
- After some search, it looks like the options have to be configured on the `io` socket init directly. But those option are missing. Instead we have `timeout`, `reconnectionDelay` and `reconnectionDelayMax`.

So I assume this should be something like this:

```typescript
const socket = io('https://staging.api.kidways.fr', {
  transports: ['websocket'],
  timeout: 20000,
  reconnectionDelay: 5000,
  reconnectionDelayMax:20000,
});
```

Source: https://github.com/socketio/socket.io-client/blob/8372591652260f88987c467b94573a144ee4db63/docs/API.md#manager

Am I right? And what the exact replacement of `pingInterval` in that case?

I would like to contribute, but I want to be sure of what I am doing before. :-)

**Comment by daffl** [comment]
Indeed, the `const socketio = require('feathers-socketio');` should be `const socketio = require('@feathersjs/socketio');`. Everything else should still be the same. Note that the second block is server side code, not on the client (where setting the options for is [documented here](https://docs.feathersjs.com/api/socketio.html#app-configure-socketio-options-callback)).

**Comment by soullivaneuh** [comment]
Doh! I didn't saw the "on your server" part. :upside_down_face: 

So nothing more to configure on client side?

May be a warning note telling this code is to be placed on server-side would be great. This is not obvious has we are on the client configuration documentation.

**Comment by daffl** [comment]
I believe it does say that in the paragraph before the code sample but you are welcome to add a clarification in the pull request that fixes the import.

**Comment by soullivaneuh** [comment]
I'm not sure how to improve this.

Maybe just add some bold on the "on you server" part?

**Comment by soullivaneuh** [comment]
I added some bold on my PR, please fill free to suggest anything else.
