### ISSUE TITLE
Comment: Facebook (cookbook/authentication/facebook.md)

### ISSUE THREAD

**Issue by sizmamani** [feathersjs/docs#1469]
### Comment/Problem

I follow this and its working just fine for my web application. now the problem is a new project with ReactNative using facebook sdk and there would be no redirect (url) option.
I am able to get facebook access_token, how may I authenticate user with this token?

**Comment by daffl** [comment]
See the [Flow section in the API](https://docs.feathersjs.com/api/authentication/oauth.html#flow):

> With an existing access token, e.g. obtained through the Facebook mobile SDK

Authenticate normally with 

```js
app.service('authentication').create({
  strategy: '<name>',
  access_token: 'oauth access token'
})
```
