### ISSUE TITLE
Comment: Authentication (guides/basics/authentication.md)

### ISSUE THREAD

**Issue by danthedanman** [feathersjs/docs#1473]
### Comment/Problem

Can we see what the complete app.js file is supposed to look like at this stage?  When I attempt to run the app I get an error on const socket = io() "io is not defined"

### System configuration (optional)

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
That is the complete file. You also need to update the `public/index.html` file as shown in the [browser authentication section](https://docs.feathersjs.com/guides/basics/authentication.html#browser-authentication). This is what makes `io` available.

**Comment by danthedanman** [comment]
Got it -- was updating the wrong app.js.  Thanks!
