### ISSUE TITLE
Problem: profile.email == null - Building a frontend (guides/basics/frontend.md)

### ISSUE THREAD

**Issue by jcjveraa** [feathersjs/docs#1477]
### Comment/Problem

The Github login was 'not working' for me when copy/pasting the example project from 'your' Github repository, after following all steps.

When analyzing, I discovered that you have us do the following in the tutorial for setting up the github strategy:

```typescript
class GitHubStrategy extends OAuthStrategy {
  async getEntityData(profile: OAuthProfile, existing: any, params: Params) {
    const baseData = await super.getEntityData(profile, existing, params);

    return {
      ...baseData,
      email: profile.email
    };
  }
}
```

However, profile.email is blank when a user (such as I) has selected to 'keep email private' in their Github profile. I think this broke the workflow without thowing an error.

When I manually inserted a line to set 'profile.email' to 'Test@test.com' it worked fine.

I suggest to solve this by rewriting the example to use 'profile.login' (which is the login name of the user, jcjveraa in my case). However I have not yet attempted to do this as the 'email' field now seems hardcoded in the tutorial, and setting ```email: profile.login``` is confusing to tutorial-followers.

For completeness, the ```profile``` variable contained the following for me (_some 'id' fields 'blanked'._). Note the null for email.
```js
{
  login: 'jcjveraa',
  id: <my_id>,
  node_id: <my_node_id>',
  avatar_url: 'https://avatars0.githubusercontent.com/u/<my_id>?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/jcjveraa',
  html_url: 'https://github.com/jcjveraa',
  followers_url: 'https://api.github.com/users/jcjveraa/followers',
  following_url: 'https://api.github.com/users/jcjveraa/following{/other_user}',
  gists_url: 'https://api.github.com/users/jcjveraa/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/jcjveraa/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/jcjveraa/subscriptions',
  organizations_url: 'https://api.github.com/users/jcjveraa/orgs',
  repos_url: 'https://api.github.com/users/jcjveraa/repos',
  events_url: 'https://api.github.com/users/jcjveraa/events{/privacy}',
  received_events_url: 'https://api.github.com/users/jcjveraa/received_events',
  type: 'User',
  site_admin: false,
  name: null,
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: null,
  public_repos: 16,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: '2013-03-22T15:08:02Z',
  updated_at: '2020-05-04T09:31:50Z'
}
```
### System configuration (optional)

Following tutorial with Node 12.13.1, fresh install 4.3.0 version of feathersJS.

**Comment by daffl** [comment]
Others ran into this before as well. The issue is only really in the users service [we customized before](https://docs.feathersjs.com/guides/basics/services.html#customizing-a-service) which errors when trying to generate the avatar from a non-existent email. What we could do is

- Skip the avatar hash creation if one is already set
- Set the `avatar` in the `getEntityData` to the user profile

I think that should solve it and also automatically use your GitHub profile image as the avatar when you log in.
