### ISSUE TITLE
Comment: Writing tests (guides/basics/testing.md)

### ISSUE THREAD

**Issue by dbasilioesp** [feathersjs/docs#1479]
### Comment/Problem

This tutorial page is using Mocha, but the default is Jest.

**Comment by daffl** [comment]
The default in the generator is Mocha (see https://github.com/feathersjs/generator-feathers/blob/master/generators/app/index.js#L112) which is also shown in the summary at https://docs.feathersjs.com/guides/basics/generator.html#generating-the-application
