### ISSUE TITLE
A package for dart/Flutter eco system a flutter client.

### ISSUE THREAD

**Issue by SaabirMohamed** [feathersjs/docs#1511]
### Comment/Problem

Can we have  good package for the flutter eco system,
I have used the packages on pub.dev but they are not maintained and do not work well.
is there any plans to support Flutter clients ?
even a guide on how to use raw socket.io library to connect ... then interact with the published services.

I already run feathers servers, just would be a great and popular package to have I'm sure,

**Module versions** (especially the part that's not working):

**NodeJS version**:
any

**Operating System**:
any

**Browser Version**:
n/a

**React Native Version**:
n/a

**Module Loader**:
n/a

**Comment by daffl** [comment]
There are no plans for a Flutter client but there is extensive documentation about the Socket.io communication format in the [Socket.io direct connection API docs](https://docs.feathersjs.com/api/client/socketio.html#direct-connection). The gold and platinum [sponsorship tiers](https://github.com/sponsors/daffl) could also support development of specific packages.
