### ISSUE TITLE
syntax highlighting isn't so colourblind / accessibility compliant

### ISSUE THREAD

**Issue by kud** [feathersjs/docs#1522]
Hello,

I just discovered your framework, which seems to be really really good but the documentation and mostly the syntax highlighting is not really easy to read.

As a bit colourblind, it's tough for me to read your documentation, it really needs more contrast.

Example on background + `require()`:

![PixelSnap 2020-05-13 at 12 11 57](https://user-images.githubusercontent.com/655838/81800341-fd4f3d00-9512-11ea-9587-2a03e29561bd.png)

![image](https://user-images.githubusercontent.com/655838/81800186-b6614780-9512-11ea-9df9-2259393d1e77.png)

Could you check this please?

Contact me if you need more information / suggestion. :)

Thanks!

**Comment by daffl** [comment]
The docs redesign has finally happened and should also address this as well. Preview at https://dove.feathersjs.com/

**Comment by kud** [comment]
Wow, congrats! Amazing doc 😌
