### ISSUE TITLE
Sync user's language choice

### ISSUE THREAD

**Issue by frencojobs** [feathersjs/docs#1536]
I have to choose TypeScript on every code block and it's a tad annoying. Sync works but only when the page is refreshed. So multiple code blocks in a single page are not updated if I made a choice.

**Comment by daffl** [comment]
Agreed, I've been thinking about making this possible for a while. It would be great if someone who also has more experience with VueJS could help me look into this. I think we may have to fork the tabs component and store the language choice in localstorage.

**Comment by frencojobs** [comment]
What do you think about migrating to Docusaurus? I might be able to help you then. Check this out https://www.remotion.dev/docs/the-fundamentals as an example. We could even add type annotations like in the TypeScript website using [Twoslash](https://github.com/shikijs/twoslash).

**Comment by daffl** [comment]
Are you volunteering to migrate all the docs and add a customized tabs plugin? 😄  Having just done this for the current version from (the unmaintained) Gitbook to Vuepress I can say that it's quite a bit of work so it definitely has to be worth it. Either way, someone still has to customize the tabs plugin which I'm expecting to be a similar amount of work be it VueJS or React.

**Comment by frencojobs** [comment]
I can def volunteer in my free time. Not sure about Vuepress but in Docusaurus you can use MDX so no need to worry about tabs, just normal JSX tags. I also personally don't think it would be as much work since both of them are just Markdown-based static site generators. I'm guessing it should be fairly less work than converting from Gitbook.

**Comment by daffl** [comment]
Might be worth testing out actually. I do like MDX. It'd still need a component for tabs or some other kind of language selector though.

**Comment by frencojobs** [comment]
I'm down for it. I'll help you out as much as I can (maybe tomorrow). Should we do that in this repo as a separate branch or in a different repo?

**Comment by daffl** [comment]
Sweet! I'd recommend to fork this repo and then create a new branch based on the `dove` branch (https://github.com/feathersjs/docs/tree/dove). I'm assuming that most pages should at least render but a few of the question marks I can think of would be

- Tabs/language selector
- Syntax highlighting
- Copy to clipboad
- Search
- Edit page and create issue footer

If that initial migration works, there is a new look and website design in the works so it might also be a good opportunity to see how that could work in the docs.

**Comment by frencojobs** [comment]
Why the `dove` and not the main `crow` branch? Care to explain the difference to me?

**Comment by daffl** [comment]
It's the docs for the upcoming release so all new changes should go in there.

**Comment by daffl** [comment]
This has been done in https://github.com/feathersjs/feathers/pull/2661 and will be available in the v5 docs (see https://dove.feathersjs.com for the preview).
