### ISSUE TITLE
Some links are broken

### ISSUE THREAD

**Issue by frencojobs** [feathersjs/docs#1538]
The `getFromLocation` link in this https://docs.feathersjs.com/api/authentication/client.html#getaccesstoken is broken (well technically it doesn't have a link specified). There are quite a few of those in the documents, which could be found through a markdown linter.

![image](https://user-images.githubusercontent.com/17830687/127682693-2db5cdd9-f04f-4509-abe2-2227d78af288.png)

**Comment by daffl** [comment]
There was a link checker added in https://github.com/feathersjs/docs/pull/1284 but I believe it never actually ran during build partly because it did not work reliably with the new heading style (see https://github.com/feathersjs/docs/issues/1336)

**Comment by daffl** [comment]
The [new docs](https://dove.feathersjs.com/) do have a link checker and all links are verified to be working now.
