### ISSUE TITLE
Cookbook Suggestion: Reactjs + Feathers sockets

### ISSUE THREAD

**Issue by azampasha007** [feathersjs/docs#1582]
### Comment/Problem

I am trying to create sockets with reactjs. but there is configurations issue i think.
 here is my repo you can check: https://github.com/azampasha007/featherjs-socketio-express

### System configuration (optional)

Tell us about the applicable parts of your setup.

**Module versions** (sockets):

**NodeJS version**: 16.20.2

**Operating System**:windows

**Browser Version**:chrome updated

**React Native Version**:18.2.0

**Module Loader**:

**Comment by daffl** [comment]
You are using the wrong versions in https://github.com/azampasha007/featherjs-socketio-express/blob/main/package.json#L14-L16. They should all be `^5.0.0`. The 4.x version of `@feathersjs/socketio` is not compatible with `socket.io-client` v4.
