### ISSUE TITLE
Feathers vs LoopBack

### ISSUE THREAD

**Issue by Hongbo-Miao** [feathersjs/docs#210]
Please add a section about Feathers vs [LoopBack](http://loopback.io/) in the [Feathers vs X](http://docs.feathersjs.com/why/vs/readme.html) section, thanks!

http://loopback.io/resources/#compare might help.

**Comment by ekryski** [comment]
@Hongbo-Miao super happy to take a PR if you are willing to help. 😁

**Comment by daffl** [comment]
I'm actually wondering if we should get rid of the individual "Feathers vs. X" pages in the docs and just keep the comparison matrix. The detailed pages quickly become outdated (and imho don't really add _documentation_ value) so it might make more sense to just turn them into blog posts instead.

@feathersjs/core-team thoughts?

**Comment by marshallswain** [comment]
One aspect I do like about having them in the docs is that they eventually get updated by the community, which isn't going to happen with a blog post.  We eventually have up-to-date info once we get another PR.  It really doesn't add documentation value, though, so you're right, there.  It would be nice to keep them in a place that can be updated regularly, and just link to the comparisons in the docs.

**Comment by ekryski** [comment]
> I'm actually wondering if we should get rid of the individual "Feathers vs. X" pages in the docs and just keep the comparison matrix. The detailed pages quickly become outdated (and imho don't really add documentation value) so it might make more sense to just turn them into blog posts instead.

They should come out of the docs and maybe moved to the blog or website for SEO and educational value. Like a lot of the content in the docs they muddy things up.

In order to address @marshallswain's thought I was thinking that the next version of the site will use Metalsmith so pages like that can be in Markdown and people can still edit them.

**Comment by petermikitsh** [comment]
Saw this was still open, but Feathers vs. X comparison have been removed from the docs. 🤔

Personally, I'm a fan of them being in the docs. People may not know what Feathers is, but they may know Meteor, LoopBack, etc. A table of features with checkmarks could convey a lot to someone wanting to understand what feathers can do, without necessarily getting into the code or through reading all of the API documentation.

I think it'd be useful for people to assess their options for their tech stacks. It doesn't have to be political or suggestive that Feathers is better than any of these choices -- just a neutral, here's what we do vs. the other guys type of comparison. It's ok to have it, as long as it's as neutral as possible.

Even if not in the docs, I'd like to see the information moved somewhere -- as @ekryski suggested, a blog post would suitable, but is less discoverable.

**Comment by petermikitsh** [comment]
The legacy docs! Ya got me. They are still there indeed.

**Comment by petermikitsh** [comment]
Oh, and in the new docs too. They're still everywhere.

**Comment by dnmd** [comment]
> A table of features with checkmarks could convey a lot to someone wanting to understand what feathers can do, without necessarily getting into the code or through reading all of the API documentation.

That is indeed something I really look forward to. Doing some research/googling also doesn't result in a clear distinction, as the [table does](http://loopback.io/resources/#compare) mentioned by @Hongbo-Miao shows. From [this article](https://www.sitepoint.com/crud-app-react-redux-feathersjs/), I could extract some differences but aren't that convincing. I almost see myself "forced" to start digging in the API / docs ... Which is a bit of a pitty, but I will if I have to of course :)

Cons of using LoopBack.io over FeathersJS [(source)](https://www.sitepoint.com/crud-app-react-redux-feathersjs/)
- it does have a slight learning curve and the documentation is not easy to get along with
- it has stringent framework requirements (e.g. all models must inherit one of its built-in model class)
- if you need real-time capabilities in Loopback, be prepared to do some additional coding

**Comment by Freundschaft** [comment]
also keep in mind that http://loopback.io/doc/en/lb4/ Loopback 4 is in the pipeline and might show some differences compared to lb3

**Comment by fatman-** [comment]
I've added a brief comparison between Feathers and LoopBack; and have opened a PR here — https://github.com/feathersjs/website/pull/10

I've tried to keep the comparison brief, unbiased, and to the best of my knowledge! Please let me know if you think any changes are needed at any point. Thank you!

***

Having said that, I feel — as @daffl mentioned — a comparison matrix is the best move forward; though it could mean a significant amount of work, even if just in terms of arriving at a consensus on the key comparison metrics which should be in the matrix.

We could also find a common ground between matrix, and corresponding library specific prose; ala [deepstream/compare](https://deepstreamhub.com/compare/).

**Comment by daffl** [comment]
This has been closed via https://github.com/feathersjs/website/pull/10 by @fatman- and is available at http://localhost/development/feathersjs/website/build/feathers-vs-loopback 🎉 

If anybody is interested in implementing a comparison similar to the one on Deepstream, that would be great as well. I'm pretty much open for and happy about anything around this. A proper comparison can only be written by someone who has objectively evaluated both. I know developers love comparisons but since Feathers, unlike Deepstream, Loopback or Meteor, is not trying to eventually sell you on a product, I don't feel that I am the right person to do this.

**Comment by fatman-** [comment]
@daffl I believe you've left the localhost URL by mistake.

I'll leave the correct URL as referenced (by you) in the original PR here — https://feathersjs.com/feathers-vs-loopback

**Comment by DaddyWarbucks** [comment]
Thanks for the great work on this! I wanted to throw out one small criticism. The text on this page is hard to read, in my opinion. With the thin font, the `#666` color is very light and I struggled to read it, despite having good vision. The attached photo just changes the forst `<p>` tag to black and I think it is more legible.
<img width="1440" alt="screen shot 2018-08-24 at 11 59 10 am" src="https://user-images.githubusercontent.com/4671808/44597463-4edef380-a795-11e8-8a49-8f1f80f2daf3.png">

I don't mean to be nit-picky! Just a thought. Thanks again for this.

**Comment by daffl** [comment]
I think changing `@text-color` to `@dark-grey` in https://github.com/feathersjs/website/blob/master/assets/less/common/variables.less#L27 would be the way to go for this.
