### ISSUE TITLE
Move guides to the blog on Medium

### ISSUE THREAD

**Issue by ekryski** [feathersjs/docs#250]
The tradeoff is it's not quite as easy to edit by the community but the pros are:
- It's easier to share out/link to
- They won't clutter up the docs
- We get better SEO
- They'll get better reach when published

**Comment by daffl** [comment]
Do you just mean https://docs.feathersjs.com/guides/readme.html or also the Framework guides? I think the framework chat app guides should stay but the other ones can be moved. It's only really three (we can link to the old migration guide somewhere else) and it doesn't look like having a separate guides section is conducive to contributions there.

**Comment by ekryski** [comment]
@daffl I'm easy. I was thinking all of them initially. Trim down the docs a bit more and keep all guides in the same place but if the docs aren't getting too bloated I think we could keep them in separate section in the docs.
