### ISSUE TITLE
Add another example that expands on how to use models

### ISSUE THREAD

**Issue by frastlin** [feathersjs/docs#311]
Hello,
I am new to feathers (I have been playing with it for the last several weeks) and am just not understanding how to get MySQL or a model in general up and running.
In the
[getting started example](https://docs.feathersjs.com/getting-started/quick-start.html)
there is adding a message through http, but I didn't write any handler to add a message to the model. How did the server know to add the message passed through http to the db? I didn't even make a table.
I would like to see an example that goes through adding and searching through a model both server side and client side.
The chat example just goes through doing searches and adding entries client side.

I would also like some guidance on how to switch from using meDB to MySql.

I think there are two problems that contribute to my confusion:
1. I am used to MVC with sql, so this Aspect Oriented approach with meDB is tripping me up a little. The word "model" is not used, so I don't grasp right away that something is a "model" or has access to a db.
2. On every page there is documentation that deals with starting an app with minimal installations and not the feathers generate setup, so I am not understanding where to place different bits of code because the example doesn't look like what I have. If there were some more examples with the feathers generate setup, it would be a lot easier.

So I would love to see an example that does the following:
1. feathers generate
2. feathers generate service called messages using me db
3. Add, filter and remove messages using the server
4. add, filter and remove messages using the client (using feathers client-side app and minimal html)
5. Explain how to restrict client actions so someone doesn't crash my server
6. Migrate all the messages to MySql or Postgress and sequelize (where the db has a user)
7. Show how to add, filter and delete messages with the new DB.

The chat example doesn't deal with server side db manipulation, using another db than meDB, it uses 3rd party websites and some pretty fancy html.
It is great, but I think there is a step between hello world and the chat app that I need to have before really understanding what is going on.

Also, is it possible to use mysql without sequelize? Can I have sequelize and only use it if the built-in db api doesn't work for what I want? Does the built in API do relations?
How does one tell feathers to use a user and password for a db? I think it may be in default.json, but I'm not sure.
It looks like the "model" is app.service('users') in the chat app. But then where is the table?
Thanks,

**Comment by daffl** [comment]
The latest documentation clarifies where Feathers fits in a little more and although the generator allows to set up different databases also points out that model management is part of learning your ORM of choice and not responsibility of the Feathers documentation. Maybe someone will put up some blog posts going into more detail but I am not planning on expanding the core documentation on database usage.
