### ISSUE TITLE
feathers-docs in different languages

### ISSUE THREAD

**Issue by Lutece** [feathersjs/docs#545]
Hello, I am a Korean front-end developer.
I would like to translate feather.js so that many Korean developers can see it. Can I participate in translations?

**Comment by eddyystop** [comment]
We'd welcome community-supported translations, if they can be kept up to date. We spend all our time on Feathers core packages, so we wouldn't be able to contribute other than helping you get started.

The docs are in `feathers-docs`. They are displayed using GitBook.

**Comment by daffl** [comment]
I was thinking what we could do is create a 5 or-so page "cheat sheet" with all the important information which could be more easily translated into different languages (and maintained). Maybe we can start with German (me), Korean (@Lutece), maybe French?

**Comment by eddyystop** [comment]
I like that idea even on English.

**Comment by Lutece** [comment]
@daffl i love your idea!
how can we start? i look forward to it 👍

**Comment by daffl** [comment]
Thank you @Lutece. We have a couple of other things to wrap up first but I'm definitely planning of working on the cheatsheet. Would you be interested in starting with an introductory blog post in Korean?

**Comment by Lutece** [comment]
@daffl It is an honor to be able to contribute to feathers.js. 
Please let me know how I can participate in translation 👍

**Comment by Lutece** [comment]
I am currently creating a chat application using Feathers.js. 
I will write about the development process of my chat application and
I will introduce feathers.js with feathers-guide in my blog
If there is an issue, I will leave a comment :)

**Comment by ekryski** [comment]
@Lutece be sure to let us know so we can tweet it out and share it. I'm sure we can get some help from the community translating a cheat sheet into Spanish as well.

@daffl what did you have in mind for a cheat sheet?

- Super basic intro to the core concepts (hooks, services, events, filters, transports). Maybe pretty much just this page https://docs.feathersjs.com/guides/step-by-step/readme.html with Marshall's fancy diagram?
- Common API docs (ie. query syntax) or doing common actions like using the CLI, writing hooks, authenticating?

Converting the entire docs would be a lot of work and given how much churn we have in them (even little fixes) it might be a nightmare to do them all in different languages but I think a cheat sheet is a good idea if it is small.

**Comment by Lutece** [comment]
@ekryski  I wanna start translating the cheetsheet, how can i start?

**Comment by daffl** [comment]
I'm going to close this since it has been open for a long time and I don't think there is anything actionable. Unfortunately we don't have enough active contributors that have expressed interest in supporting this initiative or enough funds to hire professional technical translators.
