### ISSUE TITLE
Comment:Step-Basic-Rest-client

### ISSUE THREAD

**Issue by AndreMaz** [feathersjs/docs#572]
Comment:Step-Basic-Rest-client

The `rest.html` example didn't worked
Chrome's (v. 58.0.3029.96 (64-bit)) console says:

`GET file://cdnjs.cloudflare.com/ajax/libs/core-js/2.1.4/core.min.js net::ERR_FILE_NOT_FOUND
rest.html:19 GET file://unpkg.com/feathers-client@%5E1.8.0/dist/feathers.js net::ERR_FILE_NOT_FOUND
rest.html:20 GET file:///serverUrl.js net::ERR_FILE_NOT_FOUND
rest.html:22 Uncaught ReferenceError: feathers is not defined
    at rest.html:22
(anonymous) @ rest.html:22
rest.html:25 GET file:///feathers-app.js net::ERR_FILE_NOT_FOUND`

Had to change the `rest.html` to make it work. 
Before:
```html
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/core-js/2.1.4/core.min.js"></script>
<script src="//unpkg.com/feathers-client@^1.8.0/dist/feathers.js"></script>
<script src="/serverUrl.js"></script>
<script>
  const feathersClient = feathers()
      .configure(feathers.rest(serverUrl).fetch(fetch))
</script>
<script src="/feathers-app.js"></script>
```

After:
```html
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/core-js/2.1.4/core.min.js"></script>
<script src="https://unpkg.com/feathers-client@1.9.0/dist/feathers.js"></script>
<script src="./serverUrl.js"></script>
<script>
  const feathersClient = feathers()
      .configure(feathers.rest(serverUrl).fetch(fetch))
</script>
<script src="./feathers-app.js"></script>
```

**Comment by eddyystop** [comment]
Could you create a PR for this?

**Comment by eddyystop** [comment]
The examples ran fine with:
Windows 10: Chrome 57.0.2987.133
Ubuntu VM : Chrome Version 51.0.2704.106 unknown (64-bit)

Added `http://cdnjs` and `https://unpkg` throughout in https://github.com/feathersjs/feathers-docs/pull/589

**Comment by onlinetocode** [comment]
Worked on macOS 10.12.6 & newest Chrome as well.

I think you opened the rest.html file by clicking on it instead of pointing your browser to http://localhost:3030/rest.html. When I click on the file I can reproduce your console output.

**Comment by eddyystop** [comment]
Thanks for this info @onlinetocode. I wouldn't have thought of it.
