### ISSUE TITLE
Write a guide on transitioning to microservices

### ISSUE THREAD

**Issue by ekryski** [feathersjs/docs#70]
What I mean by this is how you transition from your "monolithic" feathers app to a few smaller services. Again, using the context of that chat app will work great. We should be able to split it up into 3 services:
- A user service
- An auth service
- A message service

We can show how they all talk to each other and possibly how you can now deploy this on Heroku or something.

**Comment by kulakowka** [comment]
I have an account in [trace](https://trace.risingstack.com/). I can give it to you if it is necessary for the application.

**Comment by churcho** [comment]
How is this coming along? I need something like this to give me a broad view of how I can structure my application as I delve into this. +1

**Comment by ekryski** [comment]
Haven't started it yet. We've already used feathers-sync but we've been tackling other more pressing things. The main release issue is more or less in priority order so it might be a bit before the core team gets to it.

**Comment by kuncevic** [comment]
@ekryski saying 

> A user service
> An auth service
> A message service

are you missing the `gateway service` ?

**Comment by marshallswain** [comment]
I think it was implied.

**Comment by daffl** [comment]
Closing in favour of https://github.com/feathersjs/feathers/issues/157
