### ISSUE TITLE
Fix mixed-auth guide.  hook.params.token is missing

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/docs#710]
For some reason `hook.params.token` doesn't exist, anymore, so the guide is broken.  I can't follow my own guide anymore.  :(

**Comment by ekryski** [comment]
Really? @marshallswain it might be due to the recent changes we made to auth but I was pretty sure it was just `hook.data.token` that was removed. Any ideas on why it might be an issue? I haven't upgraded to the latest auth modules yet. Was likely going to be doing that today.

**Comment by marshallswain** [comment]
Yeah.  I can't think of anything we did that would have caused this.  I'll dive in sometime soon.

**Comment by ekryski** [comment]
Okay keep me posted. If I come across anything in the upgrade I'll be sure to put up PRs or issues.

**Comment by ekryski** [comment]
@marshallswain where did you end up with this?

**Comment by Ryanthegiantlion** [comment]
I believe the token died in this commit:

https://github.com/feathersjs/feathers-authentication/commit/97f8004ddf0abc802c218500fdbdffd7e2de1ade#diff-1fdf421c05c1140f6d71444ea2b27638L88

The `normalizeAuthToken` middleware which was removed would assign the token to req.feathers.token.

I don't see anything else that was added to replace that functionality.

**Comment by daffl** [comment]
Closing since this has changed in v4 authentication. See the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.
