### ISSUE TITLE
[Auth]: Guide for creating a custom local auth verifier

### ISSUE THREAD

**Issue by ekryski** [feathersjs/docs#786]
A common request is how to create a custom local auth verifier that does something other than verify `users`. Depending on your requirements, this can be as simply as changing a few config values or can be a bit more involved.

## Todo

- [ ] Show how to use local auth with a different service and `clientId` and `clientSecret` to verify "clients" or "devices" instead of users.
- [ ] Show how to take that a step further and create a custom `Verifier`.

### Related

https://github.com/feathersjs/feathers-authentication/issues/405#issuecomment-299166435

**Comment by ekryski** [comment]
If you just want to have a strategy with different key names and/or a call to a different service you can just do something like this:

```js
// In your config
{
  "auth": {
    ...
    "strategies": ["local", "client"],
    "local": {
      "name": "local",
      "usernameField": "email",
      "passwordField": "password",
      "service": "users"
    },
    "client": {
      "name": "client",
      "usernameField": "clientId",
      "passwordField": "clientSecret",
      "service": "clients" // you could just use the "users" service if you store the `clientId` and `clientSecret` on the user object. Totally up to you.
    }
  }
}

// Where you set up authentication
let config = app.get('auth');

app.configure(authentication(config))
  .configure(local(config.local))
  .configure(local(config.client))
  .configure(jwt())

// register ALL your strategies allowed for authentication
app.service('authentication').hooks({
  before: {
    create: authentication.hooks.authenticate([config.strategies]),
    remove: authentication.hooks.authenticate('jwt')
  }
});

// In your client, if you want to authenticate
// the client and not the user.
app.authenticate({
  strategy: 'client',
  clientId: 'my-client-ID',
  clientSecret: 'my-secret'
}).then({ accessToken } => {
  // do authenticated things
});
```

If you need to do something a bit more complex (ie. query by more than just the `usernameField` and `passwordField`) then you will need to also create a custom `Verifier`. There is a basic example of how to do that here: https://github.com/feathersjs/feathers-authentication-local#customizing-the-verifier.

**Comment by sarkistlt** [comment]
any progress on `Show how to take that a step further and create a custom Verifier`?
would be really great to have that example. 
Migrating project from php which was using MD5 to nodejs, and trying to use custom verifier to support both, md5 for existed users and bcrypt for new.  

Thanks!

**Comment by sarkistlt** [comment]
in my case this works:

```js
import local from '@feathersjs/authentication-local';
import bcrypt from 'bcrypt';
import crypto from 'crypto';

export default class extends local.Verifier {
  async _comparePassword(user, password) {
    return new Promise((resolve, reject) => {
      bcrypt.compare(password, user.password, (err, result) => {
        if (err) {
          return reject(err);
        }

        if (result) {
          return resolve(user);
        }
        const legacyPwSalt = 'legacy_secret';
        const hash = crypto.createHash('md5').update(`${password}${legacyPwSalt}`).digest('hex');

        if (hash === user.password) {
          return resolve(user);
        }

        return reject(false);
      });
    });
  }
}
```

**Comment by joakimstrandell** [comment]
I had to add the name property to get this working.

`
"local": {
      "name": "local",
      "entity": "user",
      "usernameField": "email",
      "passwordField": "password",
      "service": "users"
},
"client": {
      "name": "client",
      "entity": "client",
      "usernameField": "clientId",
      "passwordField": "clientSecret",
      "service": "clients"
}
`

**Comment by co2nut** [comment]
Just out of curiosity, how does this work with the existing authenticate("jwt") in before hook or services?
Currently authenticate("jwt") will look for the id in users models instead or clients model
Appreciate if there is some example for this approach 
Thanks
