### ISSUE TITLE
Comment:Step-Basic-Hooks-1

### ISSUE THREAD

**Issue by mattscooter** [feathersjs/docs#798]
Comment:Step-Basic-Hooks-1

I am getting a warning when running the example that remove has been deprecated.  This should probably be replaced with discard as per information on  https://github.com/feathersjs/feathers-hooks-common.

**Comment by eddyystop** [comment]
Thanks.

**Comment by NeiPCs** [comment]
Another error is about schema validation by ref `http://json-schema.org/draft-04/schema#`
```xl
$ node ./examples/step/01/hooks/1
C:\apps\course\copy-an-introduction\node_modules\ajv\lib\ajv.js:94
    if (!v) throw new Error('no schema with key or ref "' + schemaKeyRef + '"');
            ^

Error: no schema with key or ref "http://json-schema.org/draft-04/schema#"
```

**Comment by eddyystop** [comment]
I need some context to understand your point.
