### ISSUE TITLE
Comment:Step-Basic-Rest-client

### ISSUE THREAD

**Issue by lanzer** [feathersjs/docs#814]
Comment:Step-Basic-Rest-client

The rest.html file cannot work if you load it with your local browser unless two slight changes are made:

`<script src="/serverUrl.js"></script>
<script src="/feathers-app.js"></script>`

to:
`<script src="./serverUrl.js"></script>
<script src="./feathers-app.js"></script>`

Thank you for the guide!

**Comment by eddyystop** [comment]
It seems it runs on some browsers and not in others.

What browser are you using on which platform? Would you mind also trying Chrome?
