### ISSUE TITLE
Comment:Step-Basic-Middleware

### ISSUE THREAD

**Issue by nathandial** [feathersjs/docs#825]
It was a little unclear why the hooks all have names like "hook35".

I decided this is probably because they are typically created as anonymous functions, but took a few moments of confusion to figure out that was the reason (and I'm still less than 100% certain -- just a best-guess, but I'm pretty sure that's the main reason).

Might be nice to clarify that up-front, since this is geared toward newcomers to the framework. Coming into this from other frameworks, I think of before-hooks like "validate address" and after-hooks like "update-leaderboard" or something, not "hook10" and "hook33a".

**Comment by nathandial** [comment]
If profilers or debuggers are displaying hook-chains, it might even be nice to have some facility to give anonymous hooks developer-friendly names, if that isn't already on the roadmap.

**Comment by eddyystop** [comment]
The hooks were named in a way to related the hook diagrams. "hook35", for example, relates to the box taged with "35" on the diagram.

Typically you name hooks for what they so. So some of the feathers-hooks-common are named 'setCreatedAt', 'populate', etc.

**Comment by nathandial** [comment]
Ah, that makes sense. In the future, it might improve absorption for newcomers to the framework to have a diagram and code with typical hook names, rather than numbers. I'd volunteer to do this myself but I'm still getting a feel for the framework; not sure if I'm far enough in my understanding to not add confusion instead of clarity

**Comment by eddyystop** [comment]
The following sections "Hooks, part 1", "Hooks, part2" and "Writing Your Own Hooks" name hooks appropriately. The section you were reading was getting across the flow of hooks and not not focusing on what any of the hooks would be doing.
