### ISSUE TITLE
Comment:Step-Generators-Readme

### ISSUE THREAD

**Issue by kensilverman** [feathersjs/docs#826]
does nto work!   Using an aws image of linux - when installing generators give a postinstall error failed at the spanws-sync@1.0.15      This is a shame as fixing a black box is IMPOSSIBLE!  It should work form the get go  node sym link to nodejs     new node install ther eis no excuse for this really.  now the feathers command is not found - I assume its because the generate-cli  did not install correflty with that followup install error at the last minute - a real frustration.

**Comment by kensilverman** [comment]
postinstall sync ERROR!!!!!

**Comment by eddyystop** [comment]
| does nto work! Using an aws image of linux - when installing generators give a postinstall error failed at the spanws-sync@1.0.15 This is a shame as fixing a black box is IMPOSSIBLE!

I assume you are saying the generator threw an error in this situation. If so, could you please create an issue in the feathers-generator repo? Thanks.

**Comment by kensilverman** [comment]
not the generator, linux in response to the generator install command. It was in response to the command: 

[root@ip-172-31-20-24 home]# npm install -g feathers-cli 

Result: 

/home/ec2-user/.nvm/versions/node/v6.11.2/bin/feathers -> /home/ec2-user/.nvm/versions/node/v6.11.2/lib/node_modules/feathers-cli/bin/feathers.js 

> spawn-sync@1.0.15 postinstall /home/ec2-user/.nvm/versions/node/v6.11.2/lib/node_modules/feathers-cli/node_modules/spawn-sync 
> node postinstall 

sh: node: command not found 
/home/ec2-user/.nvm/versions/node/v6.11.2/lib 
└── (empty) 

npm ERR! Linux 4.4.30-32.54.amzn1.x86_64 
npm ERR! argv "/home/ec2-user/.nvm/versions/node/v6.11.2/bin/node" "/home/ec2-user/.nvm/versions/node/v6.11.2/bin/npm" "install" "-g" "feathers-cli" 
npm ERR! node v6.11.2 
npm ERR! npm v3.10.10 
npm ERR! file sh 
npm ERR! code ELIFECYCLE 
npm ERR! errno ENOENT 
npm ERR! syscall spawn 

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall` 
npm ERR! spawn ENOENT 
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'. 
npm ERR! Make sure you have the latest version of node.js and npm installed. 
npm ERR! If you do, this is most likely a problem with the spawn-sync package, 
npm ERR! not with npm itself. 
npm ERR! Tell the author that this fails on your system: 
npm ERR! node postinstall 
npm ERR! You can get information on how to open an issue for this project with: 
npm ERR! npm bugs spawn-sync 
npm ERR! Or if that isn't available, you can get their info via: 
npm ERR! npm owner ls spawn-sync 
npm ERR! There is likely additional logging output above. 

npm ERR! Please include the following file with any support request: 
npm ERR! /home/npm-debug.log 
npm ERR! code 1 


and tghen when I create a symlink to nodejs and then again same error and then I jsut ignore it and try to generate an app - and no go. - the "feathers" command is not found. 
----- Original Message -----

**Comment by kfern** [comment]
Could you try...

sudo npm install -g feathers-cli 

?

**Comment by kensilverman** [comment]
hmm, I wa already "root". seems to work now - only when I am not in root and not running sudo. My "node" installed to my ec2-user as .nvm/ etc ... 

but now when I run: 

[ec2-user@ip-172-31-20-24 realsafe1]$ feathers generate app 
/bin/sh: yarn: command not found 
? Project name (realsafe1) 


any problem not having yarn? seems to still ask the questions ... 

----- Original Message -----

**Comment by kensilverman** [comment]
ok, so no I go to make the project without sudo and it says error package.json permission - so If i use "sudo" now it wonrt recognize the sudo command followed by fethers - very strange. sudo by itself it recognizes and feathers it recognizes but if I type "sudo feathers ...." 

[ec2-user@ip- realsafe1]$ sudo feathers generate app 
sudo: feathers: command not found 


----- Original Message -----

**Comment by kensilverman** [comment]
ahh, maybe I have to tell sudo where the .npm node_modules is ... I guess Ill read up on how to do that. 

----- Original Message -----

**Comment by kensilverman** [comment]
got it to generate the app! doewn to only warning: 


npm WARN realsafe1@0.0.0 No repository field. 
npm WARN realsafe1@0.0.0 No license field. 


I have my fingers crossed that I will be able to just inlcude my html "somehwere" into this large generated app frame soon, and then somehow quickly figure out how to change the hooks and data stuff to actually do what I want. Read all your tutorials - bhut learning curve for me will be long I fear - just the admin stuff has taken days - Ill let you know when i am actually coding in your framewaork \ - would be nice to get there already ... 

I am a computer engineer with agi, Java, genetic algs. and machine learning experience. PHP etc ... wrote my own version of node and jquery using Ajax and threads 7 years ago. I serilized js classes into parallele php classes from client to server - it was interesting - when I wrote the android Spotwired app. But never got a smooth movement from those classes into the database - Still wrapping my hands around this seems long - hope not, cause I find it interesting. but it is always more frustrating for me to work with frameworks (ie black boxes then write my own - but just thought that maybe now it would be a faster learn. My designs are not quite general enough at this stage. So it was a toss up to make it general or use yours. 

ok back to the trying to use the generated app to make it into what i need it to be :) questions hoe do I add facebook auth to this? 

and can i take the path of just using this generated app shell and just "insert" my code, hooks, etc ... service endpoints where I need to to be? Seems like you dont actually write much with feathers - everything is already written - its just about using existing services - is that right? 



----- Original Message -----

**Comment by kensilverman** [comment]
stupid question: 

When we obtain a teams record, we want to add the team's users to the team record. This requires a hook and therefore we generate the scaffolding for a hook using: 

but you are placing that hook into hooks as populate-teams.js 

However, you are teaching that hooks that pertain only to one particular service - like the teams service - should rather be placed in the teams.hooks.js file right? 

So, shouldn't the "feathers generate hook" command be reserved for hooks that are to be performed before or after *every* service and not just for a particular service? 


----- Original Message -----

**Comment by kensilverman** [comment]
ahh ok sorry, I see now, generator adds the hook as isolated function in a file as a shell in hooks folder and it modifies the teams.hooks,js for determining flow of that hook. so in essence a hook method can be stored in hooks whether it pertains to a specific service, all services or app level hook and that logic is set/changed by the generate hooks method. Ok, interesting. 

i guess if you specify app level then that hook method flow would be changed in the apphooks.js file instead. 


ok, hope to actually add my html soon and get to put a session id into it - kind of doing this in reverse. I have html page written and I want to just somehow on server-side do a string search to add a session Id to the right parts of the html file - and then serve it up with the correct data ... 

----- Original Message -----

**Comment by kfern** [comment]
I use sudo for npm global installs only.

**Comment by kensilverman** [comment]
yeah that makes sense if your node_modules was installed above your home directory - but for some reason, mine got installed inside my ~ directory - so global instlals dont need sudo - but I chose my apps to be above the ~ dir. kind of backwards so I needed sudo for feathers to make dirs above ~. All solved now. Now i will try out your chats app and hopefully be coding soon :) 

Also, Im doing these tests on my server itself - via putty - not a local copy, so instead of local:3030 I imagine I will need to change my conf.d file to support not only interacting with 3030 but I will need to map 80 to 3030 at some point. Is that what most people do? 

----- Original Message -----

**Comment by kensilverman** [comment]
Question for you guys: 



regarding front end - Vue.js seems fastest to learn. I had wrote my own framework years ago and I just dont understand something in the new world: regarding reactivity - it seems vue and react take a whole copy of the html before and after to modify only changing parts of the DOM? That whole concept seems weird to me — my framework wrote directly to only the DOM elements that needed by requiring that you specify the DOM element ID in the AJAX so it was part of the return call. Wondering why modern frameworks dont do that? 



Figured you guys would know. Anyway I assume vue.js will mix well with feathers. but still, why dont they just make a framework like I did - you know, specify the DOM ID as a requirement in the AJAX. I was able to send to server whole typed-class objects that had matching PHP objects and that had to be dealt with by a callback in the requesting js function mapping directly to a specific DOM element. 



Thanks. 



Ken 

----- Original Message -----

**Comment by eddyystop** [comment]
You'll have to change localhost:3030 to whatever your client can "see". localhost is frequently used when the client and server are on the same machine.

"it seems vue and react take a whole copy of the html before and after to modify only changing parts of the DOM?"

True.

This way things are declarative --- you say what you want the DOM result to be --- and that avoids a lot of problems which occur when you manipulate the DOM yourself in an async world. Think: outstanding server requests successful or not, tracking mouse movements, user input and clicking. Add to that keeping the data in sync at multiple locations. Now think of detecting a bug and deducing what sequence of events caused it.

Modify the DOM is slow because you are crossing the JS-DOM boundary, so JS cycles are relatively fast.

**Comment by kensilverman** [comment]
hmm, when would the client and server be on the same machine except for testing? Maybe the client acting as some complicated daemon? 

> You'll have to change localhost:3030 to whatever your client can "see". 

So, I have an Apache instance on my remote AWS server and I would like it to remain running - and to make matters more challenging I desire the feathers project to be in a directory ABOVE the Apache default home. So it appears it matters not, as long as you use Apache's mod_proxy module to "listen" for any traffic at a particular IP at port 80 or 81 or whatever one wants and then simply proxy route it to port 3030 - which could be any node server running at port 3030 - right? So, then I tried to use every possible combination of proxyPass and ProxyPassReverse to allow the node server to receive on port 80 (from a REMOTE client - which I thought would be the most popular use of feathers). 

I tried updating a virtualhost in my main conf.d both in and out of location tags - but in all cases there is an Apache BUG upon restart that gives error "Parameter must be in the form 'key=value'." This is what I tried: 

<Location /> 
ProxyPass http://localhost:3030/ # Our port goes here 
ProxyPassReverse http://localhost:3030/ # Our port goes here 
</Location> 

or without location 

ProxyPass / http://localhost:3030/ # Our port goes here 
ProxyPassReverse / http://localhost:3030/ # Our port goes here 

or 

ProxyPass "/" "http://localhost:3030" # Our port goes here 
ProxyPassReverse "/" "http://localhost:3030" # Our port goes here 

or with location again and with key=value (which is obviously incorrect when location is specified in the tag with the slash) 

All combinations result in this error: 

AH00526: Syntax error on line 64 of /etc/httpd/conf.d/custom.conf: 
Invalid ProxyPass|ProxyPassMatch parameter. Parameter must be in the form 'key=value'. 

All proxy_mod modules are loaded via LoadModule comands in prior .conf scripts or in the same script before these calls. 

Any ideas? 

> Think: outstanding server requests successful or not, tracking mouse movements, user input and clicking. Add to that keeping the data in sync at multiple locations. 

Hmm, you may have a point about state control better in this way - then with my callback to a js function representing a single dom element. I will think about it - and I appreciate your explanation! 



----- Original Message -----

**Comment by eddyystop** [comment]
I'm not too familiar with how you'd set that up. Pehaps you can ask in Slack in #general during mid-day NA time.
