### ISSUE TITLE
Comment:Step-Basic-Socket-client

### ISSUE THREAD

**Issue by NeiPCs** [feathersjs/docs#834]
You don't have mentioned the download of socketio client lib.
I'd suggest to add the cdn one: https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.3/socket.io.js

**Comment by daffl** [comment]
@eddyystop Can correct me if I'm wrong but I think the [Changing the HTML for Feathers client WebSocket calls section](https://docs.feathersjs.com/guides/step-by-step/basic-feathers/socket-client.html#changing-the-html-for-feathers-client-websocket-calls) should instead be updated from `<script src="/socket.io.min.js"></script>` to the correct `<script src="/socket.io/socket.io.js"></script>`

**Comment by eddyystop** [comment]
I normally code what you suggest David, however I ran into issues running these examples. I don't remember what the problem was but I ended up just avoiding it.
