### ISSUE TITLE
Missing Readme file

### ISSUE THREAD

**Issue by rayfoss** [feathersjs/docs#835]
https://github.com/feathersjs/feathers-docs/blob/master/examples/offline/realtime-1/README.md 
"See README in `examples/` folder"

But there is no such thing:
https://github.com/feathersjs/feathers-docs/tree/master/examples

Under Examples/Offline https://github.com/feathersjs/feathers-docs/tree/master/examples/offline
there is a ReadMe... but it just says read the docs... which never directly reference how to run and use the examples.

critically whats missing is
1. clone this repo... not the node packages repo such as https://github.com/feathersjs/feathers-offline-realtime
2. run npm install on the offline folder
3. run npm install on every example you plan to run
4. run `npm run build` before `npm start`... which is unusual

**Comment by eddyystop** [comment]
Fair enough. Would you submit a PR?
