### ISSUE TITLE
Authentication is turned off internally: also in tests

### ISSUE THREAD

**Issue by RobIsHere** [feathersjs/docs#839]
I tried to test authentication and wondered why the authentication was passing for wrong passwords and always returned a valid jwt.

Until I discovered this line: https://github.com/feathersjs/feathers-authentication/blob/master/src/hooks/authenticate.js#L14

Turning off authentication is actually a great thing. Some hints/best practice for writing tests against the authentication in spite of this would be great.

**Comment by daffl** [comment]
This has changed in v4 authentication where `params.authentication` can be set explicitly. See the [Authentication API](https://crow.docs.feathersjs.com/api/authentication/) and the [Migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information on how to upgrade.
