### ISSUE TITLE
Comment:Step-Generators-Run not good!

### ISSUE THREAD

**Issue by DrOhjho** [feathersjs/docs#855]
Comment:Step-Generators-Run
I did the same processes as Generators write.
and Mocha test wrote as below

 1:67  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   2:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   3:61  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   4:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   5:19  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   6:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   7:34  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   8:14  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   9:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  10:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  11:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  12:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  13:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  14:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  15:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  16:11  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  17:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  18:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  19:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  20:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  21:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  22:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  23:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  24:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  25:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  26:11  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  27:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  28:14  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  29:13  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  30:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  31:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  32:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  33:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  34:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  35:3   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

✖ 95 problems (95 errors, 0 warnings)
  95 errors, 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! basic-guide-generated-project@0.0.0 eslint: `eslint src/. test/. --config .eslintrc.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the basic-guide-generated-project@0.0.0 eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\재호\AppData\Roaming\npm-cache\_logs\2017-09-25T08_35_11_449Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! basic-guide-generated-project@0.0.0 test: `npm run eslint && npm run mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the basic-guide-generated-project@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\재호\AppData\Roaming\npm-cache\_logs\2017-09-25T08_35_11_504Z-debug.log

**Comment by eddyystop** [comment]
I'm not sure what's issuing these messages. It seems to be caused by a difference between Linux and Windows end-of-lines.

I think this issue will be better answered if its placed in feathers-generator. Could you please move it there? Thank you.

**Comment by myatmin** [comment]
@DrOhjho Add `--fix` flag to `eslint` under `scripts` in `package.json`  to fix the windows line-break style problem.
