### ISSUE TITLE
Comment:Step-Basic-Hooks-1

### ISSUE THREAD

**Issue by Always-Sunny** [feathersjs/docs#862]
Comment:Step-Basic-Hooks-1

When pointing node at 1.js in the hooks folder, received this. Swapped remove with discard and got no error. 

>DEPRECATED. Use discard. (remove)

Just thought I should let you guys know so the feather-docs could be updated.

Loving the tutorial so far, thank you for all your work.

**Comment by eddyystop** [comment]
`discard` is not exactly the same as `remove`.

Thanks for the mention though.
