### ISSUE TITLE
Comment:Step-Basic-Rest-api-server

### ISSUE THREAD

**Issue by wsirota** [feathersjs/docs#869]
Comment:Step-Basic-Rest-api-server

When you follow these instructions: 
"First, start the server by running node ./examples/step/01/rest/1.js on one terminal."

you get a series of errors:
Feathers application started on port 3030
error - code: 404 message: Page not found
method: GET, url: /socket.io/?EIO=3&transport=polling&t=LyRGfAc
{}
error - code: 404 message: Page not found
method: GET, url: /socket.io/?EIO=3&transport=polling&t=LyRGgeC
{}
error - code: 404 message: Page not found
method: GET, url: /socket.io/?EIO=3&transport=polling&t=LyRGi65
{}

**Comment by eddyystop** [comment]
This is the first report of such an issue, so I think the problem lies either in how you installed the examples or where you are running this particular example from.

Make sure your current directory is the parent of `examples/`.
