### ISSUE TITLE
Comment:Step-Basic-Ahha

### ISSUE THREAD

**Issue by dearfrankg** [feathersjs/docs#870]
Comment:Step-Basic-Ahha

Consider this scenario and elaborate on how you would handle the situation:

Large project, many developers.  The font-end devs are not familiar with database calls as they normally work with REST APIs.  

Some goals for such a project might be:

- keep front-end devs from dealing with database calls
- keep the database calls centralized on the backend so you only need to search in one place to find them and so frontend devs don't need to deal with it.

**Comment by eddyystop** [comment]
The REST design is most commonly used with GET/PUT/POST/DELETE and that is DB call centric. Feathers standard design expects the client to make DB calls.

If you don't want the client to make DB calls, then I suggest you create one or more custom services on the server and have the clients communicate with that. The custom service will make the DB calls itself.

An example of this approach would be:
https://github.com/feathers-plus/feathers-authentication-management/blob/master/src/service.js

This guide, in any case, is an introduction. It never even gets around to discussing custom services.
