### ISSUE TITLE
Comment:Chat-Authentication

### ISSUE THREAD

**Issue by kilaniba** [feathersjs/docs#871]
Please when i do this configure `client.configure(feathers.authentication({
  storage: window.localStorage
}));`
 i have this error in my navigator `TypeError: feathers.authentication is not a function`

**Comment by daffl** [comment]
You have to setup the `index.html` file as shown in https://docs.feathersjs.com/guides/chat/frontend.html specifically `<script src="//unpkg.com/feathers-client@^2.0.0-pre.1/dist/feathers.js">`
