### ISSUE TITLE
Comment:Chat-Frontend

### ISSUE THREAD

**Issue by willston77** [feathersjs/docs#875]
The REST portion of the Feathers Chat app does not seem to load in the same order as the socket data... not really important but maybe to be noted?

**Comment by daffl** [comment]
Can you share some screenshots? They should come in the same way but NeDB might not guarantee the order unless you explicitly declare it.

**Comment by willston77** [comment]
Here is a screenshot; that is the case in this instance I believe.
<img width="1440" alt="different order" src="https://user-images.githubusercontent.com/16530234/31695102-65b642d4-b376-11e7-967a-9011eea056a2.png">

The window on the right was opened after the window on the left and I had sent a message on the left window before the opening the right.

**Comment by daffl** [comment]
This should be working properly now in the [new guide](https://dove.feathersjs.com/guides/) which uses SQLite.
