### ISSUE TITLE
Comment:Step-Basic-Db-connector

### ISSUE THREAD

**Issue by kreig303** [feathersjs/docs#889]
Comment:Step-Basic-Db-connector

Had to install several feathers modules... you might have missed this as you're not dealing with a "clean" install.

I sorted it by brute force i.e. i simply invoked the file via node and each exception raised i interrogated the missing require and `npm i`'d it.

**Comment by eddyystop** [comment]
The installation page https://docs.feathersjs.com/guides/step-by-step/preliminaries.html states to run `npm install`. What am I missing?
