### ISSUE TITLE
Comment: Errors

### ISSUE THREAD

**Issue by pkreipke** [feathersjs/docs#891]
Near the bottom of the page, in the text `The following options can be passed when creating a new localstorage service:` perhaps it's not `localstorage service` but `error handler`.

https://docs.feathersjs.com/api/errors.html

Side note: many pages have a "Leave Comment" link which opens an issue, but not all.

**Comment by daffl** [comment]
Definitely. Odd how that got in there. PR ("Edit this page" at the top of the page) would be very welcome.

**Comment by daffl** [comment]
Closed via #899
