### ISSUE TITLE
Comment:Step-Basic-Hooks-2

### ISSUE THREAD

**Issue by vickonovianto** [feathersjs/docs#904]
The when hook only runs if the hook method is not equal to "find". But when creating users, why the when hook doesn't run?(although the hook method when creating is "create" that is not equal to "find" but softDelete() is not executed). Please give explanation. Thank you.

**Comment by eddyystop** [comment]
The `iffElse`, `iff`, `when`, `unless` hooks do not check to see what the method (e.g. `find`) of the call if.

I suggest you start by looking into what you think that was happening.
