### ISSUE TITLE
Comment:Step-Generators-Hook

### ISSUE THREAD

**Issue by vickonovianto** [feathersjs/docs#905]
After typing `feathers generate hook`,  I enter the name of the hook, the kind of hook, and the service it will be for, and then it completes without displaying "What methods should the hook be for (select none to add it yourself)?". Why is this happening? Thank you.

**Comment by eddyystop** [comment]
Maybe @daffl can answer this. Otherwise you could ask this question in `feathers-cli`.

**Comment by daffl** [comment]
This will happen when you don't select the hook type by just pressing enter. You have to use the arrow keys to select the type.
