### ISSUE TITLE
is this the time to rename 'hook object' to 'context object'?

### ISSUE THREAD

**Issue by beeplin** [feathersjs/docs#909]
feathers v3 is coming, and this might be a good time to apply https://github.com/feathersjs-ecosystem/feathers-hooks/issues/159.

I could make a PR for the docs repo (and also some repos which include 'hook object' in warning/errormessages).

**Comment by daffl** [comment]
I've actually been working on that this weekend in https://github.com/feathersjs/docs/tree/buzzard-api-docs

**Comment by beeplin** [comment]
👍👍👍
