### ISSUE TITLE
Comment:Step-Basic-Hooks-2

### ISSUE THREAD

**Issue by sw-yx** [feathersjs/docs#918]
Comment:Step-Basic-Hooks-2

i think it would be helpful to explain more clearly what softDelete does for you. It wasn't clear to me what that new `deleted:true` field does for me.. maybe add an extra find after this to show that a soft deleted field doesnt show up by default?

**Comment by eddyystop** [comment]
Thank you. I'll be updating the docs for Buzzard soon'ish.
