### ISSUE TITLE
Comment:Step-Generators-Hook

### ISSUE THREAD

**Issue by sw-yx** [feathersjs/docs#919]
Comment:Step-Generators-Hook

there is a line `    force src/services/teams/teams.hooks.js` but this is left unexplained. you could try explaining?

**Comment by eddyystop** [comment]
That file is created by the generator and there's already a section describing the files being built and what they are for.

As for describing the contentsd of the file, first, I think they are straightforward given The Basics sections of the guide, and, second, the actual lines in the file can change whenever the generator changes and I can't keep track of that nor do I want to change the docs each time.

I do appreciate you comment but I think what's there now will have to do.
