### ISSUE TITLE
Comment:Chat-Authentication

### ISSUE THREAD

**Issue by sw-yx** [feathersjs/docs#920]
weird warnings in the generate authentication bit... `warning Pattern ["esprima-fb@~3001.0001.0000-dev-harmony-fb"] is trying to unpack in the same destination "/Users/swyx/Library/Caches/Yarn/v1/npm-esprima-fb-3001.1.0-dev-harmony-fb-b77d37abcd38ea0b77426bb8bc2922ce6b426411" as pattern ["esprima-fb@~3001.1.0-dev-harmony-fb"]. This could result in a non deterministic behavior, skipping.`

**Comment by daffl** [comment]
Do you have some more information when and how this is happening? Which command? What does `feathers --version` show?
