### ISSUE TITLE
Comment:Step-Basic-Hooks-2

### ISSUE THREAD

**Issue by clockworked247** [feathersjs/docs#921]
Personally I had trouble understanding softDelete() being attached to the before hook under "all".  I think this step might be more intuitive if you made the before hook under "remove".  

For me, when it was added under "all", I expected to see a softDelete() on "create" too, since the condition was it would run when the method != "find".

If the case is that "all" only executes on undefined methods, then it should be mentioned (it's still not clear to me, but implied by the example outcome).   Since "create" exists, does the "all" not get executed for "created" calls?  Seems so.

**Comment by eddyystop** [comment]
The only way to implement such a feature is to run a preliminary, probbing get() call before get, update, patch, remove operations. (Well, we try to optimize away the probbing get on a get.) That is why the hook has to be planned on `all`.

**Comment by clockworked247** [comment]
> The only way to implement such a feature is to run a preliminary, probbing get() call before create, get, update, patch, remove, find operations. (Well, we try to optimize away the probbing get on a get.) That is why the hook has to be planned on all.

Sure, I wasn't asking for that feature, just mentioning what the tutorial seemed to reflect.  

So I guess my confusion was due to softDelete not having set a delete prop on the "create" call.  But since you are saying all runs first, this makes sense.

I would suggest moving the call to softDelete() on "remove" instead of "all" to avoid this confusion and keep the tutorial focused on the use of softDelete().

**Comment by eddyystop** [comment]
Putting softDelete on remove would prevent it doing what it needed on get, update, patch method cal

**Comment by clockworked247** [comment]
@eddyystop Ah, that makes sense.  Clearly I have a ways to go in learning FeathersJS.   Thanks for the comments.  They've helped a lot.
