### ISSUE TITLE
File Uploads

### ISSUE THREAD

**Issue by v1shva** [feathersjs/docs#923]
Can someone explain why do you use feathers-blob to upload files? can't we just use multer  to handle file uploads without feathers-blob? Also how to do crud operations when using  blobService? (retrieving a list of items using the same service fails when using blobService)
```
/* --- server.js --- */
const multer = require('multer');
const multipartMiddleware = multer();

// Upload Service with multipart support
app.use('/uploads',

    // multer parses the file named 'uri'.
    // Without extra params the data is
    // temporarely kept in memory
    multipartMiddleware.single('uri'),

    // another middleware, this time to
    // transfer the received file to feathers
    function(req,res,next){
        req.feathers.file = req.file;
        next();
    },
    blobService({Model: blobStorage})
);
```
https://docs.feathersjs.com/guides/advanced/file-uploading.html

**Comment by daffl** [comment]
The service makes things easier to use and also allows to easily access uploaded files but you have the flexibility to implement this in whatever best suites your needs, the guide is just one example of how it can be done.
