### ISSUE TITLE
Comment:Chat-Authentication

### ISSUE THREAD

**Issue by Brian-McBride** [feathersjs/docs#924]
This line: 
> Note: Creating a user with the same email address will only work once and fail when it already exists in the database.

Is not true. When running the curl multiple users are created with the same email. This is using MongoDb as the Database.
```
curl 'http://localhost:3030/users/' -H 'Content-Type: application/json' --data-binary '{ "email": "feathers@example.com", "password": "secret" }'
```

**Comment by Brian-McBride** [comment]
Additionally, with the curl, you can add a user without a password. 😢   Or, add a user without an email and just the password. 
Auth with user/password should have some filters around that on `feathers generate authentication`?

**Comment by daffl** [comment]
The guide uses NeDB. This statement might not necessarily be true if you choose another database.
