### ISSUE TITLE
Comment:Step-Basic-Testing-Hooks: How can I stub some services with sinon?

### ISSUE THREAD

**Issue by kfern** [feathersjs/docs#925]
Hi!

In [https://github.com/josx/aor-feathers-client/blob/master/test/restClient.spec.js](https://github.com/josx/aor-feathers-client/blob/master/test/restClient.spec.js) there is an example of how to stub a generic service.

How can I stub diferent services with sinon? I can't find any example

Thanks in advance

**Comment by eddyystop** [comment]
I have written my own stubs for Feathers and do not recommend stubs. Services are tied into hooks and auth. These days I just spin my a new Feathers app for each test.

You can "instrument" a service doing something like this https://github.com/feathers-plus/feathers-hooks-common/blob/master/tests/services/soft-delete.test.js#L29-L38

The stubs I used but really don't recommend are in https://github.com/eddyystop/feathers-tests-fake-app-users

You'll have to figure out what you want to do with or without Sinon.

**Comment by kfern** [comment]
Thank you @eddyystop 

Sinon is a very useful tool for unit tests and imho we should be able to use it. 

https://github.com/eddyystop/feathers-tests-fake-app-users looks like Sinon

Why is not it recommended to use it?

**Comment by eddyystop** [comment]
I've used Sinon.

Feathers services are integrated with the hooks, so if your tests depend on hooks firing then its not easy to fake/mock/etc. a service. You can however instrument it as I showed above.

**Comment by kfern** [comment]
Ok. Thank you again
