### ISSUE TITLE
Help @Step-Basic-Readme

### ISSUE THREAD

**Issue by XBelenus** [feathersjs/docs#927]
Hello,
this question seems so dumb but i can't figure it out, after generating my new app, where do i configure feathers to be be served over http2.createServer();

**Comment by eddyystop** [comment]
@daffl  ^^^

**Comment by XBelenus** [comment]
i founded a way by following the [https section](https://docs.feathersjs.com/api/express.html#https) mixed with [Node's http2 example](https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_server_side_example) but i cannot see my index.html file, i receive a: 
- "ERR_SSL_PROTOCOL_ERROR" when browsing to https://localhost:3030 
- "ERR_INVALID_HTTP_RESPONSE" when browsing to http://localhost:3030
i have tried to listen port 443 too but the same happened.
Otherwise when i use https instead, every things works fine. i can access the file throught https.
i modified the /src/index.js file as follow:

`/* eslint-disable no-console */
const logger = require('winston');
const app = require('./app');
const port = app.get('port');
const fs = require('fs');
var http2 = require('http2');
const server = http2.createServer({
  key: fs.readFileSync('key.pem'),
  cert: fs.readFileSync('cert.pem')
}, app).listen(port);

process.on('unhandledRejection', (reason, p) =>
  logger.error('Unhandled Rejection at: Promise ', p, reason)
);

server.on('listening', () =>
  logger.info('Feathers application started on http://%s:%d', app.get('host'), port)
);

server.on('stream', (stream, headers)=>{
  stream.respond({
    'content-type': 'text/html',
    ':status': 200
  });
  stream.respondWithFile(app.get('public')+'index.html',{
    'content-type': 'text/plain'
  });
  stream.end();
})`

**Comment by eddyystop** [comment]
PM daffl on Slack to look at this issue. I'll be interested in knowing the result of any discussion.

**Comment by daffl** [comment]
HTTP2 support is being tracked in https://github.com/feathersjs/feathers/issues/369. I don't believe Express officially has it yet but as with everything related to Feathers and HTTP, everything that works with Express will work as well.

Once Buzzard is out we will also look into adding transport providers that use the Node HTTP/HTTP2 modules directly.

**Comment by corymsmith** [comment]
The issue you are seeing is probably because HTTP2 requires SSL encryption and I think most browsers only support HTTP2 over SSL

**Comment by XBelenus** [comment]
It works fine with the SPDY implementation for Express, i just replaced "require('http2')" with "require('spdy')" and it works fine now! i will also look at KoaJS it support http2 native module and is written by the Express team.
![h2spdy](https://user-images.githubusercontent.com/33655831/33402664-8dbb1aa8-d55d-11e7-8e1f-7b90eacb6f31.PNG)
Thank you again FeathersJS is amazing !
