### ISSUE TITLE
documentation fixes

### ISSUE THREAD

**Issue by edwardsmarkf** [feathersjs/docs#934]
minor version issue:
https://github.com/feathersjs/docs/compare/master...edwardsmarkf:patch-1

suggested code fix:
https://github.com/feathersjs/docs/compare/master...edwardsmarkf:patch-2

**Comment by eddyystop** [comment]
Even if its the server mutating the data, shouldn't the client's be informed of it?

**Comment by edwardsmarkf** [comment]
in patch-2 i am trying to get the example at the bottom of the page working correctly.

https://docs.feathersjs.com/guides/step-by-step/basic-feathers/real-time.html#

the documentation at the bottom of thise page states:

_For example, we could send users events only to authenticated users and remove password from the payload by adding this to the server code:_

```const users = app.service('users');
users.filter((data, connection) => {
  delete data.password;
  return connection.user ? data : false;
});```

**Comment by eddyystop** [comment]
This seems to be a question about using filters rather than a comment on the docs. Perhaps @daffl should comment.

**Comment by edwardsmarkf** [comment]
i apologize,  i should have explained this more carefully.  

https://docs.feathersjs.com/guides/step-by-step/basic-feathers/real-time.html

the code at the bottom of the page was intended to remove the passwords:

_For example, we could send users events only to authenticated users and remove password from the payload by adding this to the server code:_

however, the code is removing everything, not just the password.  i believe this was happening because `return connection.user ?` does not exist in the example, only `connection.provider` does.

**Comment by edwardsmarkf** [comment]
you might want to include this too:

https://github.com/feathersjs/docs/compare/master...edwardsmarkf:patch-4
in addition to:
https://github.com/feathersjs/docs/compare/master...edwardsmarkf:patch-1
