### ISSUE TITLE
Comment:Chat-Authentication

### ISSUE THREAD

**Issue by emahuni** [feathersjs/docs#936]
This part _"The returned token can now be used to authenticate the user it was created for by adding it to the Authorization header of new HTTP requests."_  is clear, **but is not happening** in the code or at least it's not said how the token is being re-used by feathers on every other HTTP requests or socket polls.
```js
client.authenticate({
  strategy: 'local',
  email: 'feathers@example.com',
  password: 'secret'
}).then((token) => {
  console.log('User is logged in', token);

  // At this point we have a valid token, so we can fetch restricted data.
  messages.find().then(page => page.data.forEach(addMessage));
  messages.on('created', addMessage);
});
```
I am **new** to Feathers, but from the above snippet `client.authenticate...` seems to be the actual login process. Somehow the token is stored to local storage and then it is never used again in the tute, ever! I think there should be explanation and usage example of how the token is used from the local storage when the actual login process is not done again later (after refresh or revisit etc) or at least explain if it is being used behind the scenes. This would upend the above claim true _"The returned token can now be used to authenticate..."_

What i expected was that on revisit, refresh etc, the token would be used to authenticate the user instead of logging in again. The `client.authenticate...`  part is supposed to have an if statement that would check if the authentication token is available in localstorage... if avalaible then the app would simply use the token to authenticate the user and then run the code in the promise resolution above, else it does the login part `client.authenticate...`  then  run the code in the promise resolution above. I think that's how apps in the real world work and is expected by Feathers newbies like me.

Please correct me if I am wrong or explain and provide code in the tute for others, if I am not wrong, on how to use the localstorage token to authenticate the user without logging in again. With clear commenting done in the code about what is going on, _like user logs in using log in form_ etc, I think that would help a lot for us new beaks to understand expected authentication at first sight in Feathers. 

This framework is just superb and I am actually migrating from Laravel to this. I wanted something in Node environment that rivals Laravel and I think this is it. It's actually better out of the box. Nice job guys.

p.s. I thought the idea of tokens was to login once and then use the token every other time without actually providing the password again until logged out etc.

**Comment by daffl** [comment]
Thank you! The token is used but you have to call `.authenticate()` (with no parameters) again to try and authenticate with the token from localStorage. [The chat application](https://github.com/feathersjs/feathers-chat) does this and the [new guides](http://buzzard.docs.feathersjs.com/guides/chat/readme.html) which will be released shortly will reflect that.
