### ISSUE TITLE
Custom auth api key strategy recipe not working

### ISSUE THREAD

**Issue by ThePesta** [feathersjs/docs#943]
In `guides/auth/recipe.custom-auth-strategy.md`, under the [`Creating a Custom API Key Auth Strategy`](https://github.com/feathersjs/docs/blob/master/guides/auth/recipe.custom-auth-strategy.md#creating-a-custom-api-key-auth-strategy) section

When the strategy is used, the options are `undefined` and errors [here](https://github.com/feathersjs/authentication/blob/dd182da97c34a060198b2932800801da17dfc8f9/lib/socket/handler.js#L95) as property `entities` is accessed of `undefined`

```this.passport.options('apiKey', {})``` should be added where the strategy is defined as per @daffl 's [solution](https://feathersjs.slack.com/archives/C0HJE6A65/p1513097462000314?thread_ts=1513072975.000004&cid=C0HJE6A65)

**Comment by daffl** [comment]
Closed via https://github.com/feathersjs/docs/commit/7617cf6ad66c5e3057814d5985259b89e7b8b907
