### ISSUE TITLE
Comment:Chat-Frontend 'created' event handled does not fire

### ISSUE THREAD

**Issue by aral** [feathersjs/docs#952]
I must be missing something very basic here but I’ve been looking into this for over an hour now and I just can’t seem to get the 'created' event to fire no matter what I do. 

## What _does_ work:

1. The promise resolves:

```
const createMessage = function() {
  console.log('Creating message …')
  messages.create({
    name: 'Test user',
    text: 'Hello, world!'
  }).then ((result) => console.log(result))
}
```

Output:

`[Log] {name: "Test user", text: "Hello, world!", _id: "lTMVYmncDYQewION"} (app.js, line 27)`

2. All hooks seem to firing on the server side. Console output:

```
> feathers-chat@0.0.0 start /Users/aral/sandbox/feathers-chat
> node src/

info: Feathers application started on http://localhost:3030
debug: before app.service('messages').create()
debug: Hook Context {
  "type": "before",
  "method": "create",
  "path": "messages",
  "params": {
    "query": {},
    "route": {},
    "provider": "socketio"
  },
  "data": {
    "name": "Test user",
    "text": "Hello, world!"
  }
}
debug: after app.service('messages').create()
```

3. The message is successfully persisted in the database and correctly retrieved on next reload.

## What doesn’t work

The 'created' handler does not get called.

## Source

Full source of app.js:

```
const socket = io()
const client = feathers()
// client.configure(feathers.hooks())

client.configure(feathers.socketio(socket))

const messages = client.service('messages')

messages.on('created', message =>
  alert(`New message from ${message.name}: ${message.text}`)
);

const createMessage = function() {
  console.log('Creating message …')
  messages.create({
    name: 'Test user',
    text: 'Hello, world!'
  }).then ((result) => console.log(result))
}

setTimeout(createMessage, 1000)

messages.find().then(page => console.log('Current messages are', page))
```

Full source of index.html:

```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=0" />
    <title>Feathers chat</title>
    <link rel="shortcut icon" href="favicon.ico">
  </head>
  <body>
    <div id="app" class="flex flex-column"></div>
    <script type="text/javascript" src="//unpkg.com/socket.io-client@1.7.3/dist/socket.io.js"></script>
    <script type="text/javascript" src="//unpkg.com/@feathersjs/client@^3.0.0/dist/feathers.js"></script>
    <script type="text/javascript" src="app.js"></script>
  </body>
</html>
```

## Environment details

**Node version:** LTS (v8.9.3)
**Feathers version:** 3.3.0
**Platform:** macOS (latest High Sierra)
**Tested and reproduced in browsers:** Safari 10.13.1, Firefox 57.0.1

PS. I had to comment out the `client.configure(feathers.hooks())` line as it was giving an error with the latest feathersjs client library as per the versions in the HTML file above. (I was seeing the same behaviour described here – sans the hooks-related error – with the client library used in the tutorial itself before trying the newer versions to see if that was the issue.)

Any thoughts? I must be missing something very simple here.

**Comment by daffl** [comment]
For using v3 please follow the [guides of the next version](https://buzzard.docs.feathersjs.com/guides/readme.html) which will be published shortly. There, how to use channels and publish events is described [here](https://buzzard.docs.feathersjs.com/guides/basics/real-time.html#channels) and [here](https://buzzard.docs.feathersjs.com/guides/chat/authentication.html#securing-real-time-events).

**Comment by aral** [comment]
Thanks, @daffl :)

**Comment by smlnbyv** [comment]
@aral how did you have resolved that issue with 'created' event ? 
I am using mongoDB and Mongoose

**Comment by bengitiger** [comment]
Thanks, @daffl  :)

**Comment by AdamGerthel** [comment]
@smlnbyv You need to publish the channel ([see comment](https://github.com/feathersjs/docs/issues/952#issuecomment-352492528)
