### ISSUE TITLE
hooks-common.md missing from current master

### ISSUE THREAD

**Issue by jnhghy** [feathersjs/docs#966]
At this point there are links pointing to api/hooks-common.md here: https://docs.feathersjs.com/guides/auth/recipe.mixed-auth.html the link for iff takes you to a 404:
https://docs.feathersjs.com/api/hooks-common.md#iff

I checked an older commit ( 6 nov 2017 ) and the hooks-common.md file exists in it, not sure if the docs should update and remove the links to the resources or if the file needs to be brought back in the current master. I tend to think the later is better but I haven't checked the latest version of the hooks-common.md file to see in which date it was removed.

**Comment by daffl** [comment]
Thank you. The docs have been moved to [feathers-plus.github.io/v1/feathers-hooks-common/](https://feathers-plus.github.io/v1/feathers-hooks-common/). I updated the links you mentioned.
