### ISSUE TITLE
Comment: Adding authentication (guides/chat/authentication.md) channel.js already set up correctly

### ISSUE THREAD

**Issue by aral** [feathersjs/docs#984]
Under “Securing real-time events”, it says: “by updating src/channels.js to this”.

The code that follows is exactly that the generator already created (Feathers version 3.4.1) (apart from a few commented out lines that are removed in the code listing but exist in the generated file).

Should this section be removed or re-written?

**Comment by aral** [comment]
Just saw the comment in the paragraph following the code listing:

“This is almost the same as the original file except for the line return app.channel('authenticated'); being commented in app.publish(). Now only authenticated users will receive real-time updates.”

On 3.4.1, the line was not commented out.

**Comment by daffl** [comment]
Yep, I changed it in https://github.com/feathersjs/generator-feathers/pull/324 but didn't get to updating the guide.
